//! The frame a daemon answers a hello with, compared with the pinned original's
//! (`tests/fixtures/original-hello-vectors.json`, generated by
//! `gen-original-hello-vectors.cjs`). The daemon under test starts from a home
//! with the original's server id and speech features switched off, as the
//! original's was; the only difference allowed is the machine's host name,
//! which the fixture records from the machine it ran on, and `features.workspaceLabels`
//! (tracked gap DWLABEL-001, the label service is not ported).

mod common;

use std::collections::HashMap;
use std::fs;
use std::net::TcpStream;
use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use serde_json::{Value, json};
use spocky_daemon::daemon::{DaemonEnv, NoSessionBackend, start};
use spocky_daemon::log::{Logger, NullLogger};
use tungstenite::Message;
use tungstenite::client::IntoClientRequest;

#[test]
fn server_info_matches_the_original_byte_for_byte() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixtures/original-hello-vectors.json")).unwrap();
    assert_eq!(fixture["node"], "v22.20.0");
    let case = &fixture["results"][0];
    // The one tracked difference, DWLABEL-001: the workspace label service is not
    // ported, so the feature is not advertised. Any other difference fails.
    let expected = case["frames"][0]
        .as_str()
        .unwrap()
        .replace("\"workspaceLabels\":true,", "");

    let root = tempfile::tempdir().unwrap();
    let home = root.path().join("home");
    fs::create_dir_all(&home).unwrap();
    fs::write(home.join("server-id"), "srv_test\n").unwrap();
    fs::write(
        home.join("config.json"),
        json!({
            "daemon": {"relay": {"enabled": false}},
            "features": {"dictation": {"enabled": false}, "voiceMode": {"enabled": false}}
        })
        .to_string(),
    )
    .unwrap();
    let listen = "127.0.0.1:0";
    common::assert_disposable_listen(listen);
    let vars: HashMap<String, String> = HashMap::from([
        ("PASEO_HOME".to_owned(), home.display().to_string()),
        ("PASEO_LISTEN".to_owned(), listen.to_owned()),
    ]);
    let env = DaemonEnv::new(
        vars,
        PathBuf::from("/"),
        Some(PathBuf::from("/Users/example")),
    );
    let logger: Arc<dyn Logger> = Arc::new(NullLogger);
    let daemon = start(&env, Arc::new(NoSessionBackend), &logger).unwrap();

    let address = daemon.listen().to_owned();
    let request = format!("ws://{address}/ws").into_client_request().unwrap();
    let stream = TcpStream::connect(&address).unwrap();
    stream
        .set_read_timeout(Some(Duration::from_secs(5)))
        .unwrap();
    let (mut ws, _) = tungstenite::client(request, stream).unwrap();
    ws.send(Message::text(case["hello"].to_string())).unwrap();
    let Message::Text(frame) = ws.read().unwrap() else {
        panic!("expected a text frame");
    };
    let local = gethostname::gethostname().to_string_lossy().into_owned();
    let original_host = fixture["results"][0]["frames"][0]
        .as_str()
        .and_then(|text| serde_json::from_str::<Value>(text).ok())
        .map(|frame| {
            frame["message"]["payload"]["hostname"]
                .as_str()
                .unwrap()
                .to_owned()
        })
        .unwrap();
    // Only the `hostname` field's value differs; nothing else in the frame is rewritten.
    let local_field = format!("\"hostname\":{}", serde_json::to_string(&local).unwrap());
    let original_field = format!(
        "\"hostname\":{}",
        serde_json::to_string(&original_host).unwrap()
    );
    assert_eq!(
        frame.as_str().matches(&local_field).count(),
        1,
        "hostname field"
    );
    assert_eq!(
        frame.as_str().replacen(&local_field, &original_field, 1),
        expected,
        "server_info frame (DWLABEL-001 aside)"
    );
    drop(ws);
    daemon.stop();
}
