//! Raw HTTP exchanges against the daemon, compared with the captured output of
//! the pinned original daemon (`tests/fixtures/original-http-vectors.json`,
//! generated by `gen-original-http-vectors.cjs`: Paseo 5de45e2 under Node
//! 22.20.0 on disposable loopback ports). Each case is a sequence of requests
//! on one socket, the exact response bytes, and whether the server closed the
//! socket afterwards. The daemon under test takes the captured server id,
//! hostname, version and listen address, so the bytes can be equal.

mod common;

use std::collections::HashSet;
use std::io::{ErrorKind, Read, Write};
use std::net::TcpStream;
use std::sync::Arc;
use std::time::{Duration, Instant};

use serde_json::Value;
use spocky_contracts::ws::ServerId;
use spocky_daemon::admission::PasswordVerifier;
use spocky_daemon::daemon::NoSessionBackend;
use spocky_daemon::log::NullLogger;
use spocky_daemon::server::{ListenHandle, Server, ServerConfig, ServerDeps, Timeouts};

struct Exact;

impl PasswordVerifier for Exact {
    fn verify(&self, password: &str, password_hash: &str) -> bool {
        password == "secret" && password_hash == "hash"
    }
}

struct Running {
    server: Server,
    listener: ListenHandle,
    port: u16,
}

fn start(fixture: &Value, secure: bool) -> Running {
    let captured_port = fixture["ports"][if secure { "secured" } else { "open" }]
        .as_u64()
        .unwrap();
    let config = ServerConfig {
        server_id: ServerId::new(fixture["serverId"].as_str().unwrap()).unwrap(),
        daemon_version: fixture["version"].as_str().unwrap().to_owned(),
        hostname: fixture["hostname"].as_str().unwrap().to_owned(),
        hostnames: None,
        allowed_origins: HashSet::from([
            "paseo://app".to_owned(),
            format!("http://127.0.0.1:{captured_port}"),
            format!("http://localhost:{captured_port}"),
        ]),
        password_hash: secure.then(|| "hash".to_owned()),
        desktop_managed: false,
        workspace_labels: false,
        advertise_daemon_status_rpc: true,
        advertise_relay_config: true,
        start_paused: false,
        capabilities: None,
        timeouts: Timeouts {
            hello: Duration::from_secs(5),
            reconnect_grace: Duration::from_secs(5),
            application_lease: Duration::from_secs(5),
            close: Duration::from_secs(1),
        },
    };
    let server = Server::new(
        config,
        ServerDeps {
            backend: Arc::new(NoSessionBackend),
            verifier: Arc::new(Exact),
            local_credential: Arc::new(|| None),
            logger: Arc::new(NullLogger),
        },
    );
    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let handle = server.serve_tcp(listener).unwrap();
    let port = handle.local_addr().unwrap().port();
    common::assert_disposable_listen(&format!("127.0.0.1:{port}"));
    // The captured status body carries this address, whatever port is bound.
    server.set_listen(&format!("127.0.0.1:{captured_port}"), true);
    Running {
        server,
        listener: handle,
        port,
    }
}

/// Reads one response: the head, then `Content-Length` bytes unless the
/// request was a HEAD or the status carries no body.
fn read_response(stream: &mut TcpStream, pending: &mut Vec<u8>, method: &str) -> String {
    let deadline = Instant::now() + Duration::from_secs(5);
    loop {
        let text = String::from_utf8_lossy(pending).into_owned();
        if let Some(end) = text.find("\r\n\r\n") {
            let head = &text[..end];
            let status: u16 = head.split(' ').nth(1).unwrap().parse().unwrap();
            let length = head
                .lines()
                .find_map(|line| {
                    let (name, value) = line.split_once(':')?;
                    name.eq_ignore_ascii_case("content-length")
                        .then(|| value.trim().parse::<usize>().unwrap())
                })
                .unwrap_or(0);
            let bodyless = method == "HEAD" || status == 304 || status == 204;
            let need = end + 4 + if bodyless { 0 } else { length };
            if pending.len() >= need {
                let response = String::from_utf8_lossy(&pending[..need]).into_owned();
                pending.drain(..need);
                return response;
            }
        }
        assert!(Instant::now() < deadline, "no complete response: {text:?}");
        let mut chunk = [0_u8; 4096];
        match stream.read(&mut chunk) {
            Ok(0) => panic!("closed before a full response: {text:?}"),
            Ok(read) => pending.extend_from_slice(&chunk[..read]),
            Err(error) if matches!(error.kind(), ErrorKind::WouldBlock | ErrorKind::TimedOut) => {}
            Err(error) => panic!("{error}"),
        }
    }
}

/// The parts of a response that differ per run: the `Date` header, and the
/// timestamp (hence the `ETag`) of a 200 from `/api/health`.
fn normalize(response: &str, target: &str) -> String {
    let mut out = Vec::new();
    let health_ok = response.starts_with("HTTP/1.1 200")
        && target.to_ascii_lowercase().starts_with("/api/health");
    let (head, body) = response.split_once("\r\n\r\n").unwrap();
    for line in head.split("\r\n") {
        if line.starts_with("Date: ") {
            out.push("Date: <date>".to_owned());
        } else if health_ok && line.starts_with("ETag: ") {
            out.push("ETag: <etag>".to_owned());
        } else {
            out.push(line.to_owned());
        }
    }
    let body = if health_ok && body.contains("\"timestamp\":\"") {
        let start = body.find("\"timestamp\":\"").unwrap() + 13;
        format!("{}<timestamp>{}", &body[..start], &body[start + 24..])
    } else {
        body.to_owned()
    };
    format!("{}\r\n\r\n{body}", out.join("\r\n"))
}

/// Whether the server closed the socket within a short wait.
fn closed_by_server(stream: &mut TcpStream) -> bool {
    stream
        .set_read_timeout(Some(Duration::from_millis(400)))
        .unwrap();
    let mut byte = [0_u8; 1];
    match stream.read(&mut byte) {
        Ok(0) => true,
        Ok(_) => panic!("unexpected bytes after the last response"),
        Err(error) if matches!(error.kind(), ErrorKind::WouldBlock | ErrorKind::TimedOut) => false,
        Err(_) => true,
    }
}

#[test]
fn http_exchanges_match_the_captured_original_daemon_bytes() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixtures/original-http-vectors.json")).unwrap();
    assert_eq!(fixture["node"], "v22.20.0");
    assert!(
        fixture["original"]
            .as_str()
            .unwrap()
            .ends_with("5de45e208690b0efc51c59a585ae9729325a9204")
    );
    let open = start(&fixture, false);
    let secured = start(&fixture, true);
    let cases = fixture["cases"].as_array().unwrap();
    assert!(cases.len() >= 41);
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let running = if case["secure"].as_bool().unwrap() {
            &secured
        } else {
            &open
        };
        let mut stream = TcpStream::connect(("127.0.0.1", running.port)).unwrap();
        stream
            .set_read_timeout(Some(Duration::from_millis(200)))
            .unwrap();
        let mut pending = Vec::new();
        let requests = case["requests"].as_array().unwrap();
        let responses = case["responses"].as_array().unwrap();
        for (request, expected) in requests.iter().zip(responses) {
            let request = request.as_str().unwrap();
            let method = request.split(' ').next().unwrap();
            let target = request.split(' ').nth(1).unwrap();
            stream.write_all(request.as_bytes()).unwrap();
            let actual = read_response(&mut stream, &mut pending, method);
            assert_eq!(
                normalize(&actual, target),
                normalize(expected.as_str().unwrap(), target),
                "{name}: {request:?}"
            );
        }
        assert_eq!(
            closed_by_server(&mut stream),
            case["closed"].as_bool().unwrap(),
            "{name}: socket closed afterwards"
        );
    }
    for running in [open, secured] {
        running.server.close();
        running.listener.stop();
    }
}
