//! Raw WebSocket exchanges against the daemon, compared with what the pinned
//! original daemon sent for the same bytes
//! (`tests/fixtures/original-ws-vectors.json`, generated by
//! `gen-original-ws-vectors.cjs`): upgrade responses, close codes and reasons,
//! hello rejection, a second hello, receiver errors, and reconnect.
//!
//! Cases replay in the captured order against one daemon, as they ran against
//! the original, because a client id reused by a later case resumes the
//! earlier session. Client frames use an all-zero mask key. Server frames are
//! compared as opcode and exact payload. Allowed differences, none of them in
//! a close code, reason or frame order: the machine's host name in
//! `server_info`, and `features.workspaceLabels` (tracked gap DWLABEL-001).
//!
//! The session layer is a stand-in that accepts every schema-valid session
//! frame and delivers a protocol failure as the status/error frame the
//! original's session delivery sends, with the failure's text as its message.

mod common;

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;
use std::fs;
use std::io::{Read, Write};
use std::net::TcpStream;
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};

use serde_json::{Value, json};
use spocky_contracts::text::JsText;
use spocky_contracts::ws::{
    DaemonPermission, ServerCapabilities, ServerCapabilityState, ServerId, ServerVoiceCapabilities,
};
use spocky_daemon::admission::PasswordVerifier;
use spocky_daemon::daemon::{DaemonEnv, start};
use spocky_daemon::log::{Logger, NullLogger};
use spocky_daemon::server::{Server, ServerConfig, ServerDeps, Timeouts};
use spocky_daemon::session_api::{
    ProtocolFailure, SessionBackend, SessionHandle, SessionOpen, SessionSink, SocketId,
};

struct Exact;

impl PasswordVerifier for Exact {
    fn verify(&self, password: &str, password_hash: &str) -> bool {
        password == "secret" && password_hash == "hash"
    }
}

struct Stand;

struct StandHandle {
    sink: Arc<dyn SessionSink>,
}

impl SessionHandle for StandHandle {
    fn session_id(&self) -> String {
        "session".to_owned()
    }
    fn permissions(&self) -> Vec<DaemonPermission> {
        DaemonPermission::ALL.to_vec()
    }
    fn update_client_capabilities(&self, _: Option<&Value>, _: SocketId, _: Option<&str>) {}
    fn update_app_version(&self, _: &str) {}
    fn handle_message(&self, _: Value, _: SocketId) {}
    fn protocol_failure(&self, source: SocketId, failure: ProtocolFailure) {
        self.sink.send_to_source(
            source,
            &json!({"type": "status", "payload": {"status": "error", "message": failure.error}}),
        );
    }
    fn socket_detached(&self, _: SocketId) {}
    fn cleanup(&self) {}
}

impl SessionBackend for Stand {
    fn open(&self, open: SessionOpen) -> Arc<dyn SessionHandle> {
        Arc::new(StandHandle { sink: open.sink })
    }
    fn validate_inbound(&self, _: &Value) -> Result<(), String> {
        Ok(())
    }
}

/// What one connection saw: bytes received and whether the server closed it.
struct Wire {
    stream: TcpStream,
    received: Arc<Mutex<Vec<u8>>>,
    closed: Arc<AtomicBool>,
}

impl Wire {
    fn open(port: u16) -> Self {
        let stream = TcpStream::connect(("127.0.0.1", port)).unwrap();
        let received = Arc::new(Mutex::new(Vec::new()));
        let closed = Arc::new(AtomicBool::new(false));
        let mut reader = stream.try_clone().unwrap();
        let (sink, flag) = (Arc::clone(&received), Arc::clone(&closed));
        thread::spawn(move || {
            let mut chunk = [0_u8; 4096];
            loop {
                match reader.read(&mut chunk) {
                    Ok(0) | Err(_) => {
                        flag.store(true, Ordering::SeqCst);
                        return;
                    }
                    Ok(read) => sink.lock().unwrap().extend_from_slice(&chunk[..read]),
                }
            }
        });
        Self {
            stream,
            received,
            closed,
        }
    }
}

fn upgrade_request(headers: &Value, target: &str) -> String {
    let mut all: Vec<(String, Option<String>)> = vec![
        ("Host".into(), Some("localhost".into())),
        ("Upgrade".into(), Some("websocket".into())),
        ("Connection".into(), Some("Upgrade".into())),
        (
            "Sec-WebSocket-Key".into(),
            Some("dGhlIHNhbXBsZSBub25jZQ==".into()),
        ),
        ("Sec-WebSocket-Version".into(), Some("13".into())),
    ];
    if let Some(extra) = headers.as_object() {
        for (name, value) in extra {
            let value = value.as_str().map(str::to_owned);
            match all.iter_mut().find(|(known, _)| known == name) {
                Some(entry) => entry.1 = value,
                None => all.push((name.clone(), value)),
            }
        }
    }
    let mut text = format!("GET {target} HTTP/1.1\r\n");
    for (name, value) in all {
        if let Some(value) = value {
            let _ = write!(text, "{name}: {value}\r\n");
        }
    }
    text.push_str("\r\n");
    text
}

fn encode_frame(opcode: u8, payload: &[u8]) -> Vec<u8> {
    let mut frame = vec![0x80 | opcode];
    match payload.len() {
        len if len < 126 => frame.push(0x80 | u8::try_from(len).unwrap()),
        len if len < 65_536 => {
            frame.push(0x80 | 0x7e);
            frame.extend_from_slice(&u16::try_from(len).unwrap().to_be_bytes());
        }
        len => {
            frame.push(0x80 | 0x7f);
            frame.extend_from_slice(&u64::try_from(len).unwrap().to_be_bytes());
        }
    }
    frame.extend_from_slice(&[0, 0, 0, 0]);
    frame.extend_from_slice(payload);
    frame
}

fn hex_bytes(text: &str) -> Vec<u8> {
    (0..text.len() / 2)
        .map(|index| u8::from_str_radix(&text[index * 2..index * 2 + 2], 16).unwrap())
        .collect()
}

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().fold(String::new(), |mut out, byte| {
        let _ = write!(out, "{byte:02x}");
        out
    })
}

/// The events the generator records: the 101 head or the aborted response,
/// then each server frame.
fn events(received: &[u8]) -> Vec<Value> {
    let text: String = received.iter().map(|&byte| char::from(byte)).collect();
    let Some(end) = text.find("\r\n\r\n") else {
        return if received.is_empty() {
            Vec::new()
        } else {
            vec![json!({"t": "http", "text": text})]
        };
    };
    if !text.starts_with("HTTP/1.1 101") {
        return vec![json!({"t": "http", "text": text})];
    }
    let mut out = vec![json!({"t": "head", "text": &text[..end + 4]})];
    let mut rest = &received[end + 4..];
    while rest.len() >= 2 {
        let opcode = rest[0] & 0x0f;
        let (length, offset) = match rest[1] & 0x7f {
            126 if rest.len() >= 4 => (usize::from(u16::from_be_bytes([rest[2], rest[3]])), 4),
            127 if rest.len() >= 10 => (
                usize::try_from(u64::from_be_bytes(rest[2..10].try_into().unwrap())).unwrap(),
                10,
            ),
            126 | 127 => break,
            short => (usize::from(short), 2),
        };
        if rest.len() < offset + length {
            break;
        }
        let payload = &rest[offset..offset + length];
        out.push(match opcode {
            0x8 => json!({
                "t": "close",
                "code": (payload.len() >= 2).then(|| u16::from_be_bytes([payload[0], payload[1]])),
                "reason": String::from_utf8_lossy(payload.get(2..).unwrap_or_default())
            }),
            0x1 => json!({"t": "text", "text": String::from_utf8_lossy(payload)}),
            0x9 => json!({"t": "ping", "hex": to_hex(payload)}),
            0xa => json!({"t": "pong", "hex": to_hex(payload)}),
            other => json!({"t": "frame", "opcode": other, "hex": to_hex(payload)}),
        });
        rest = &rest[offset + length..];
    }
    out
}

fn run(port: u16, steps: &[Value]) -> HashMap<String, (bool, Vec<Value>)> {
    let mut wires: Vec<(String, Wire)> = Vec::new();
    let find = |wires: &Vec<(String, Wire)>, name: &str| {
        wires.iter().position(|(known, _)| known == name).unwrap()
    };
    for step in steps {
        let action = step[0].as_str().unwrap();
        if action == "wait" {
            thread::sleep(Duration::from_millis(step[1].as_u64().unwrap()));
            continue;
        }
        let name = step[1].as_str().unwrap();
        if action == "connect" {
            let mut wire = Wire::open(port);
            let headers = step.get(2).cloned().unwrap_or(Value::Null);
            let target = step.get(3).and_then(Value::as_str).unwrap_or("/ws");
            wire.stream
                .write_all(upgrade_request(&headers, target).as_bytes())
                .unwrap();
            wires.push((name.to_owned(), wire));
            thread::sleep(Duration::from_millis(250));
            continue;
        }
        let index = find(&wires, name);
        let wire = &mut wires[index].1;
        match action {
            "text" => wire
                .stream
                .write_all(&encode_frame(0x1, step[2].as_str().unwrap().as_bytes())),
            "binary" => wire
                .stream
                .write_all(&encode_frame(0x2, &hex_bytes(step[2].as_str().unwrap()))),
            "ping" => wire
                .stream
                .write_all(&encode_frame(0x9, &hex_bytes(step[2].as_str().unwrap()))),
            "close" => {
                let mut payload = u16::try_from(step[2].as_u64().unwrap())
                    .unwrap()
                    .to_be_bytes()
                    .to_vec();
                payload.extend_from_slice(step[3].as_str().unwrap().as_bytes());
                wire.stream.write_all(&encode_frame(0x8, &payload))
            }
            "raw" => wire.stream.write_all(&hex_bytes(step[2].as_str().unwrap())),
            "destroy" => {
                let _ = wire.stream.shutdown(std::net::Shutdown::Both);
                wire.closed.store(true, Ordering::SeqCst);
                Ok(())
            }
            "await_close" => {
                let deadline = Instant::now() + Duration::from_millis(step[2].as_u64().unwrap());
                while !wire.closed.load(Ordering::SeqCst) && Instant::now() < deadline {
                    thread::sleep(Duration::from_millis(50));
                }
                Ok(())
            }
            other => panic!("unknown action {other}"),
        }
        .unwrap();
        thread::sleep(Duration::from_millis(250));
    }
    thread::sleep(Duration::from_millis(500));
    wires
        .into_iter()
        .map(|(name, wire)| {
            let closed = wire.closed.load(Ordering::SeqCst);
            let _ = wire.stream.shutdown(std::net::Shutdown::Both);
            thread::sleep(Duration::from_millis(20));
            let received = wire.received.lock().unwrap().clone();
            (name, (closed, events(&received)))
        })
        .collect()
}

/// `server_info` as captured, with the two allowed differences removed.
fn normalize(event: &Value, captured_host: &str, local_host: &str) -> Value {
    let mut event = event.clone();
    if event["t"] == "text"
        && let Some(text) = event["text"].as_str()
        && text.contains("\"status\":\"server_info\"")
    {
        // Only the `hostname` field's value and the tracked `workspaceLabels`
        // feature are rewritten.
        let field = |name: &str| format!("\"hostname\":{}", serde_json::to_string(name).unwrap());
        let text = text
            .replacen(&field(local_host), &field(captured_host), 1)
            .replacen("\"workspaceLabels\":true,", "", 1);
        event["text"] = Value::String(text);
    }
    event
}

fn open_daemon() -> (spocky_daemon::daemon::RunningDaemon, u16, tempfile::TempDir) {
    let root = tempfile::tempdir().unwrap();
    let home = root.path().join("home");
    fs::create_dir_all(&home).unwrap();
    fs::write(home.join("server-id"), "srv_test\n").unwrap();
    fs::write(
        home.join("config.json"),
        json!({
            "daemon": {"relay": {"enabled": false}},
            "features": {"dictation": {"enabled": false}, "voiceMode": {"enabled": false}}
        })
        .to_string(),
    )
    .unwrap();
    let listen = "127.0.0.1:0";
    common::assert_disposable_listen(listen);
    let vars: HashMap<String, String> = HashMap::from([
        ("PASEO_HOME".to_owned(), home.display().to_string()),
        ("PASEO_LISTEN".to_owned(), listen.to_owned()),
    ]);
    let env = DaemonEnv::new(
        vars,
        PathBuf::from("/"),
        Some(PathBuf::from("/Users/example")),
    );
    let logger: Arc<dyn Logger> = Arc::new(NullLogger);
    let daemon = start(&env, Arc::new(Stand), &logger).unwrap();
    let port: u16 = daemon.listen().rsplit(':').next().unwrap().parse().unwrap();
    (daemon, port, root)
}

fn secured_server() -> (Server, spocky_daemon::server::ListenHandle, u16) {
    let capabilities = ServerCapabilities {
        voice: ServerVoiceCapabilities {
            dictation: ServerCapabilityState {
                enabled: false,
                reason: JsText::new("Dictation is disabled in daemon config."),
            },
            voice: ServerCapabilityState {
                enabled: false,
                reason: JsText::new("Realtime voice is disabled in daemon config."),
            },
        },
    };
    let config = ServerConfig {
        server_id: ServerId::new("srv_test").unwrap(),
        daemon_version: "0.10.0".to_owned(),
        hostname: gethostname::gethostname().to_string_lossy().into_owned(),
        hostnames: None,
        allowed_origins: HashSet::new(),
        password_hash: Some("hash".to_owned()),
        desktop_managed: false,
        workspace_labels: false,
        advertise_daemon_status_rpc: true,
        advertise_relay_config: true,
        start_paused: false,
        capabilities: Some(capabilities),
        timeouts: Timeouts::default(),
    };
    let server = Server::new(
        config,
        ServerDeps {
            backend: Arc::new(Stand),
            verifier: Arc::new(Exact),
            local_credential: Arc::new(|| None),
            logger: Arc::new(NullLogger),
        },
    );
    let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let handle = server.serve_tcp(listener).unwrap();
    let port = handle.local_addr().unwrap().port();
    common::assert_disposable_listen(&format!("127.0.0.1:{port}"));
    server.set_listen(&format!("127.0.0.1:{port}"), true);
    server.begin_accepting_connections();
    (server, handle, port)
}

#[test]
fn websocket_exchanges_match_the_original_daemon() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixtures/original-ws-vectors.json")).unwrap();
    assert_eq!(fixture["node"], "v22.20.0");
    let captured_host = fixture["hostname"].as_str().unwrap().to_owned();
    let local_host = gethostname::gethostname().to_string_lossy().into_owned();
    let (daemon, open_port, _home) = open_daemon();
    let (server, handle, secured_port) = secured_server();
    let cases = fixture["cases"].as_array().unwrap();
    assert!(cases.len() >= 49);
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let port = if case["secure"].as_bool().unwrap() {
            secured_port
        } else {
            open_port
        };
        let actual = run(port, case["steps"].as_array().unwrap());
        let expected = case["events"].as_object().unwrap();
        assert_eq!(actual.len(), expected.len(), "{name}: connections");
        for (conn, captured) in expected {
            let (closed, frames) = &actual[conn];
            let want: Vec<Value> = captured["frames"]
                .as_array()
                .unwrap()
                .iter()
                .map(|event| normalize(event, &captured_host, &local_host))
                .collect();
            let got: Vec<Value> = frames
                .iter()
                .map(|event| normalize(event, &captured_host, &local_host))
                .collect();
            assert_eq!(got, want, "{name}: connection {conn}");
            assert_eq!(
                *closed,
                captured["closed"].as_bool().unwrap(),
                "{name}: connection {conn} closed by the server"
            );
        }
    }
    server.close();
    handle.stop();
    daemon.stop();
}
