//! `load_persisted_config` against what the pinned original's
//! `loadPersistedConfig` returned or threw for the same config.json text
//! (`tests/fixtures/original-config-vectors.json`, generated by
//! `gen-original-config-vectors.mjs` under Node 22.20.0). Error messages are
//! compared whole; the disposable config path is the only masked part.

mod common;

use serde_json::Value;
use spocky_daemon::config_file::load_persisted_config;
use spocky_daemon::hostnames::Hostnames;
use spocky_daemon::log::NullLogger;

#[test]
fn config_acceptance_and_refusal_match_the_original() {
    let fixture: Value =
        serde_json::from_str(include_str!("fixtures/original-config-vectors.json")).unwrap();
    assert_eq!(fixture["node"], "v22.20.0");
    common::assert_fixture_provenance(&fixture);
    let cases = fixture["cases"].as_array().unwrap();
    assert!(cases.len() >= 26);
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let home = tempfile::tempdir().unwrap();
        let file = home.path().join("config.json");
        std::fs::write(&file, case["text"].as_str().unwrap()).unwrap();
        let result = load_persisted_config(home.path(), &NullLogger);
        if let Some(expected) = case.get("error").and_then(Value::as_str) {
            let error = result.expect_err(name).0;
            assert_eq!(
                error,
                expected.replace("<config>", &file.display().to_string()),
                "{name}"
            );
            continue;
        }
        let config = result.unwrap_or_else(|error| panic!("{name}: {error}"));
        let ok = &case["ok"];
        assert_eq!(ok["listen"].as_str(), config.listen.as_deref(), "{name}");
        let hostnames = match &config.hostnames {
            None => Value::Null,
            Some(Hostnames::Any) => Value::Bool(true),
            Some(Hostnames::Patterns(patterns)) => serde_json::json!(patterns),
        };
        assert_eq!(ok["hostnames"], hostnames, "{name}");
        let origins = if ok["corsAllowedOrigins"].is_null() {
            Vec::new()
        } else {
            serde_json::from_value::<Vec<String>>(ok["corsAllowedOrigins"].clone()).unwrap()
        };
        assert_eq!(origins, config.cors_allowed_origins, "{name}");
        assert_eq!(
            ok["password"].as_str(),
            config.auth_password.as_deref(),
            "{name}"
        );
    }
}
