[package]
name = "spocky-daemon-relay"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.94"

[dependencies]
spocky-contracts = { path = "../spocky-contracts" }
spocky-crypto = { path = "../spocky-crypto" }

[dev-dependencies]
serde_json = "1.0.145"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
pedantic = "deny"
