// Generated by scripts/phase3/contracts-zod.mjs; do not edit.
//! `PersistedConfigSchema` of pinned Paseo `5de45e2` as [`crate::zod`]
//! schemas, with the `provider-config.js` schemas its `agents.providers`
//! preprocess parses with. Generated from the built
//! `packages/server/dist/server/server/persisted-config.js` (SHA-256
//! `5d8500251e8c114b7ae0dcb3af9ca505c092211939e16795830731ca52ea2e8c`) and `packages/protocol/dist/provider-config.js`
//! (SHA-256 `8f8cb1be7745538110d4f99df871c09092b6db37b9295929937640101f226082`).

use std::sync::LazyLock;

use crate::js_value::JsValue;
use crate::zod::{NumberCheck, Refinement, Schema, StringCheck, Transform, UnknownKeys};

/// SHA-256 of the `persisted-config.js` this file was generated from.
pub const PERSISTED_CONFIG_JS_SHA256: &str = "5d8500251e8c114b7ae0dcb3af9ca505c092211939e16795830731ca52ea2e8c";

/// `PersistedConfigSchema`.
#[must_use]
pub fn persisted_config() -> &'static Schema {
    &PERSISTED_CONFIG
}

/// `ProviderOverridesSchema`.
#[must_use]
pub fn provider_overrides() -> &'static Schema {
    &PROVIDER_OVERRIDES
}

/// `AgentProviderRuntimeSettingsMapSchema`.
#[must_use]
pub fn agent_provider_runtime_settings_map() -> &'static Schema {
    &AGENT_PROVIDER_RUNTIME_SETTINGS_MAP
}

static SHARED_1: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Object(
        vec![
            ("apiKey", Schema::Optional(Box::new(Schema::String(vec![
                StringCheck::Trim,
                StringCheck::Min(1),
            ])))),
            ("baseUrl", Schema::Optional(Box::new(Schema::String(vec![
                StringCheck::Trim,
                StringCheck::Min(1),
            ])))),
        ],
        UnknownKeys::Strict,
    )
});

static PROVIDER_PROFILE_MODEL: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Object(
        vec![
            ("id", Schema::String(vec![
                StringCheck::Min(1),
            ])),
            ("label", Schema::String(vec![
                StringCheck::Min(1),
            ])),
            ("description", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("isDefault", Schema::Optional(Box::new(Schema::Boolean))),
            ("thinkingOptions", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Object(
                vec![
                    ("id", Schema::String(vec![])),
                    ("label", Schema::String(vec![])),
                    ("description", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("isDefault", Schema::Optional(Box::new(Schema::Boolean))),
                ],
                UnknownKeys::Allow,
            )))))),
        ],
        UnknownKeys::Allow,
    )
});

static PROVIDER_OVERRIDES: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Refined(
        Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Object(
        vec![
            ("extends", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("label", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("description", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("command", Schema::Optional(Box::new(Schema::Refined(
                Box::new(Schema::Array(Box::new(Schema::String(vec![
                StringCheck::Min(1),
            ])))),
                vec![
                    Refinement::MinLength(1),
                ],
            )))),
            ("env", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::String(vec![])))))),
            ("params", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))),
            ("models", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Lazy(|| &PROVIDER_PROFILE_MODEL)))))),
            ("additionalModels", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Lazy(|| &PROVIDER_PROFILE_MODEL)))))),
            ("disallowedTools", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
            ("paseoTools", Schema::Optional(Box::new(Schema::Object(
                vec![
                    ("enabled", Schema::Optional(Box::new(Schema::Boolean))),
                    ("disabledTools", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
                ],
                UnknownKeys::Allow,
            )))),
            ("enabled", Schema::Optional(Box::new(Schema::Boolean))),
            ("order", Schema::Optional(Box::new(Schema::Number(vec![])))),
        ],
        UnknownKeys::Allow,
    )))),
        vec![
            Refinement::SuperRefine(crate::config::provider_overrides_issues),
        ],
    )
});

static SHARED_4: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Pipe(Box::new(Schema::String(vec![
        StringCheck::Trim,
        StringCheck::Lower,
    ])), Box::new(Schema::Enum(&["openai", "local"])))
});

static LOG_LEVEL: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Enum(&["trace", "debug", "info", "warn", "error", "fatal"])
});

static LOG_FORMAT: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Enum(&["pretty", "json"])
});

static PERSISTED_CONFIG: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Object(
        vec![
            ("$schema", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("version", Schema::Optional(Box::new(Schema::Literal(vec![
                JsValue::Number(1.0),
            ])))),
            ("daemon", Schema::Optional(Box::new(Schema::Pipe(Box::new(Schema::Object(
                vec![
                    ("listen", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("hostnames", Schema::Optional(Box::new(Schema::Union(vec![
                        Schema::Literal(vec![
                            JsValue::Bool(true),
                        ]),
                        Schema::Array(Box::new(Schema::String(vec![]))),
                    ])))),
                    ("allowedHosts", Schema::Optional(Box::new(Schema::Union(vec![
                        Schema::Literal(vec![
                            JsValue::Bool(true),
                        ]),
                        Schema::Array(Box::new(Schema::String(vec![]))),
                    ])))),
                    ("trustedProxies", Schema::Optional(Box::new(Schema::Union(vec![
                        Schema::Literal(vec![
                            JsValue::Bool(true),
                        ]),
                        Schema::Array(Box::new(Schema::String(vec![]))),
                    ])))),
                    ("mcp", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("enabled", Schema::Optional(Box::new(Schema::Boolean))),
                            ("injectIntoAgents", Schema::Optional(Box::new(Schema::Boolean))),
                        ],
                        UnknownKeys::Allow,
                    )))),
                    ("browserTools", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("enabled", Schema::Optional(Box::new(Schema::Boolean))),
                        ],
                        UnknownKeys::Allow,
                    )))),
                    ("git", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("maxProcessesPerSecond", Schema::Optional(Box::new(Schema::Number(vec![
                                NumberCheck::Int,
                                NumberCheck::Gt(0.0),
                            ])))),
                            ("maxProcessConcurrency", Schema::Optional(Box::new(Schema::Number(vec![
                                NumberCheck::Int,
                                NumberCheck::Gt(0.0),
                            ])))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                    ("autoArchiveAfterMerge", Schema::Optional(Box::new(Schema::Boolean))),
                    ("enableTerminalAgentHooks", Schema::Optional(Box::new(Schema::Boolean))),
                    ("appendSystemPrompt", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("terminalProfiles", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Object(
                        vec![
                            ("id", Schema::String(vec![])),
                            ("name", Schema::String(vec![])),
                            ("command", Schema::String(vec![])),
                            ("args", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
                            ("icon", Schema::Optional(Box::new(Schema::String(vec![])))),
                        ],
                        UnknownKeys::Allow,
                    )))))),
                    ("agentProfiles", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Object(
                        vec![
                            ("id", Schema::String(vec![])),
                            ("name", Schema::String(vec![])),
                            ("icon", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("color", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("provider", Schema::String(vec![])),
                            ("model", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("modeId", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("thinkingOptionId", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("featureValues", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))),
                            ("notes", Schema::Optional(Box::new(Schema::String(vec![])))),
                        ],
                        UnknownKeys::Allow,
                    )))))),
                    ("cors", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("allowedOrigins", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                    ("relay", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("enabled", Schema::Optional(Box::new(Schema::Boolean))),
                            ("endpoint", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("publicEndpoint", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("useTls", Schema::Optional(Box::new(Schema::Boolean))),
                            ("publicUseTls", Schema::Optional(Box::new(Schema::Boolean))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                    ("serviceProxy", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("enabled", Schema::Optional(Box::new(Schema::Boolean))),
                            ("listen", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("publicBaseUrl", Schema::Optional(Box::new(Schema::String(vec![
                                StringCheck::Url,
                            ])))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                    ("auth", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("password", Schema::Optional(Box::new(Schema::String(vec![
                                StringCheck::Format {
                format: "regex",
                pattern: r"/^\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}$/",
                test: crate::config::is_bcrypt_hash,
                message: Some("Expected a bcrypt hash"),
            },
                            ])))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                ],
                UnknownKeys::Strict,
            )), Box::new(Schema::Transform(Transform::NoIssue)))))),
            ("app", Schema::Optional(Box::new(Schema::Object(
                vec![
                    ("baseUrl", Schema::Optional(Box::new(Schema::String(vec![])))),
                ],
                UnknownKeys::Strict,
            )))),
            ("providers", Schema::Optional(Box::new(Schema::Object(
                vec![
                    ("openai", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("apiKey", Schema::Optional(Box::new(Schema::String(vec![
                                StringCheck::Min(1),
                            ])))),
                            ("baseUrl", Schema::Optional(Box::new(Schema::String(vec![
                                StringCheck::Trim,
                                StringCheck::Min(1),
                            ])))),
                            ("stt", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_1)))),
                            ("tts", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_1)))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                    ("local", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("modelsDir", Schema::Optional(Box::new(Schema::String(vec![
                                StringCheck::Min(1),
                            ])))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                ],
                UnknownKeys::Strict,
            )))),
            ("pluginsEnabled", Schema::Optional(Box::new(Schema::Boolean))),
            ("plugins", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![
                StringCheck::Format {
        format: "regex",
        pattern: "/^[a-z][a-z0-9-]*$/",
        test: crate::config::is_provider_id,
        message: None,
    },
            ])), Box::new(Schema::Discriminated(
                "source",
                vec![
                    ("directory", Schema::Object(
                        vec![
                            ("source", Schema::Literal(vec![
                                JsValue::String("directory".to_owned()),
                            ])),
                            ("path", Schema::String(vec![
                                StringCheck::Min(1),
                            ])),
                            ("enabled", Schema::Optional(Box::new(Schema::Boolean))),
                        ],
                        UnknownKeys::Strict,
                    )),
                ],
            )))))),
            ("worktrees", Schema::Optional(Box::new(Schema::Object(
                vec![
                    ("root", Schema::Optional(Box::new(Schema::String(vec![
                        StringCheck::Min(1),
                    ])))),
                    ("servicePorts", Schema::Optional(Box::new(Schema::Refined(
                        Box::new(Schema::Object(
                        vec![
                            ("range", Schema::Optional(Box::new(Schema::String(vec![
                                StringCheck::Trim,
                                StringCheck::Format {
                format: "regex",
                pattern: r"/^(\d{1,5})-(\d{1,5})$/",
                test: crate::config::is_tcp_port_range,
                message: None,
            },
                            ])))),
                            ("portScript", Schema::Optional(Box::new(Schema::String(vec![
                                StringCheck::Trim,
                                StringCheck::Min(1),
                            ])))),
                        ],
                        UnknownKeys::Strict,
                    )),
                        vec![
                            Refinement::Refine {
                test: crate::config::has_range_or_port_script,
                message: "Expected range or portScript",
            },
                            Refinement::Refine {
                test: crate::config::is_inclusive_port_range,
                message: "Expected an inclusive TCP port range from 1-65535",
            },
                        ],
                    )))),
                ],
                UnknownKeys::Strict,
            )))),
            ("agents", Schema::Optional(Box::new(Schema::Object(
                vec![
                    ("providers", Schema::Optional(Box::new(Schema::Pipe(Box::new(Schema::Transform(Transform::Map(crate::config::normalize_agent_providers))), Box::new(Schema::Lazy(|| &PROVIDER_OVERRIDES)))))),
                    ("catalogRefreshTimeoutMs", Schema::Optional(Box::new(Schema::Number(vec![
                        NumberCheck::Int,
                        NumberCheck::Gt(0.0),
                        NumberCheck::Lte(2_147_483_647.0),
                    ])))),
                    ("metadataGeneration", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("providers", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Object(
                                vec![
                                    ("provider", Schema::String(vec![
                                        StringCheck::Min(1),
                                    ])),
                                    ("model", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Min(1),
                                    ])))),
                                    ("thinkingOptionId", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Min(1),
                                    ])))),
                                ],
                                UnknownKeys::Strict,
                            )))))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                    ("skills", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("selection", Schema::Optional(Box::new(Schema::Discriminated(
                                "mode",
                                vec![
                                    ("all", Schema::Object(
                                        vec![
                                            ("mode", Schema::Literal(vec![
                                                JsValue::String("all".to_owned()),
                                            ])),
                                        ],
                                        UnknownKeys::Strict,
                                    )),
                                    ("custom", Schema::Object(
                                        vec![
                                            ("mode", Schema::Literal(vec![
                                                JsValue::String("custom".to_owned()),
                                            ])),
                                            ("skills", Schema::Array(Box::new(Schema::String(vec![])))),
                                        ],
                                        UnknownKeys::Strict,
                                    )),
                                ],
                            )))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                ],
                UnknownKeys::Strict,
            )))),
            ("features", Schema::Optional(Box::new(Schema::Object(
                vec![
                    ("dictation", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("enabled", Schema::Optional(Box::new(Schema::Boolean))),
                            ("stt", Schema::Optional(Box::new(Schema::Object(
                                vec![
                                    ("provider", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_4)))),
                                    ("model", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Min(1),
                                    ])))),
                                    ("language", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Trim,
                                        StringCheck::Min(1),
                                    ])))),
                                    ("confidenceThreshold", Schema::Optional(Box::new(Schema::Number(vec![])))),
                                ],
                                UnknownKeys::Strict,
                            )))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                    ("voiceMode", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("enabled", Schema::Optional(Box::new(Schema::Boolean))),
                            ("llm", Schema::Optional(Box::new(Schema::Object(
                                vec![
                                    ("provider", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("model", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Min(1),
                                    ])))),
                                ],
                                UnknownKeys::Strict,
                            )))),
                            ("stt", Schema::Optional(Box::new(Schema::Object(
                                vec![
                                    ("provider", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_4)))),
                                    ("model", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Min(1),
                                    ])))),
                                    ("language", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Trim,
                                        StringCheck::Min(1),
                                    ])))),
                                ],
                                UnknownKeys::Strict,
                            )))),
                            ("turnDetection", Schema::Optional(Box::new(Schema::Object(
                                vec![
                                    ("provider", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_4)))),
                                ],
                                UnknownKeys::Strict,
                            )))),
                            ("tts", Schema::Optional(Box::new(Schema::Object(
                                vec![
                                    ("provider", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_4)))),
                                    ("model", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Min(1),
                                    ])))),
                                    ("voice", Schema::Optional(Box::new(Schema::Enum(&["alloy", "echo", "fable", "onyx", "nova", "shimmer"])))),
                                    ("speakerId", Schema::Optional(Box::new(Schema::Number(vec![
                                        NumberCheck::Int,
                                    ])))),
                                    ("speed", Schema::Optional(Box::new(Schema::Number(vec![])))),
                                ],
                                UnknownKeys::Strict,
                            )))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                    ("webUi", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("enabled", Schema::Optional(Box::new(Schema::Boolean))),
                            ("distDir", Schema::Optional(Box::new(Schema::String(vec![
                                StringCheck::Min(1),
                            ])))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                ],
                UnknownKeys::Strict,
            )))),
            ("log", Schema::Optional(Box::new(Schema::Object(
                vec![
                    ("level", Schema::Optional(Box::new(Schema::Lazy(|| &LOG_LEVEL)))),
                    ("format", Schema::Optional(Box::new(Schema::Lazy(|| &LOG_FORMAT)))),
                    ("console", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("level", Schema::Optional(Box::new(Schema::Lazy(|| &LOG_LEVEL)))),
                            ("format", Schema::Optional(Box::new(Schema::Lazy(|| &LOG_FORMAT)))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                    ("file", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("level", Schema::Optional(Box::new(Schema::Lazy(|| &LOG_LEVEL)))),
                            ("path", Schema::Optional(Box::new(Schema::String(vec![
                                StringCheck::Min(1),
                            ])))),
                            ("rotate", Schema::Optional(Box::new(Schema::Object(
                                vec![
                                    ("maxSize", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Min(1),
                                    ])))),
                                    ("maxFiles", Schema::Optional(Box::new(Schema::Number(vec![
                                        NumberCheck::Int,
                                        NumberCheck::Gt(0.0),
                                    ])))),
                                ],
                                UnknownKeys::Strict,
                            )))),
                        ],
                        UnknownKeys::Strict,
                    )))),
                ],
                UnknownKeys::Strict,
            )))),
        ],
        UnknownKeys::Strict,
    )
});

static AGENT_PROVIDER_RUNTIME_SETTINGS_MAP: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Refined(
        Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Object(
        vec![
            ("command", Schema::Optional(Box::new(Schema::Discriminated(
                "mode",
                vec![
                    ("default", Schema::Object(
                        vec![
                            ("mode", Schema::Literal(vec![
                                JsValue::String("default".to_owned()),
                            ])),
                        ],
                        UnknownKeys::Allow,
                    )),
                    ("append", Schema::Object(
                        vec![
                            ("mode", Schema::Literal(vec![
                                JsValue::String("append".to_owned()),
                            ])),
                            ("args", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
                        ],
                        UnknownKeys::Allow,
                    )),
                    ("replace", Schema::Object(
                        vec![
                            ("mode", Schema::Literal(vec![
                                JsValue::String("replace".to_owned()),
                            ])),
                            ("argv", Schema::Refined(
                                Box::new(Schema::Array(Box::new(Schema::String(vec![
                                StringCheck::Min(1),
                            ])))),
                                vec![
                                    Refinement::MinLength(1),
                                ],
                            )),
                        ],
                        UnknownKeys::Allow,
                    )),
                ],
            )))),
            ("env", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::String(vec![])))))),
            ("disallowedTools", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
        ],
        UnknownKeys::Allow,
    )))),
        vec![
            Refinement::SuperRefine(crate::config::runtime_settings_map_issues),
        ],
    )
});
