// Generated by scripts/phase3/contracts-zod.mjs; do not edit.
//! `CreationSnapshotSchema` of pinned Paseo `5de45e2` as [`crate::zod`]
//! issue schemas, so a creation receipt that fails to parse reports the
//! `ZodError` the baseline throws. Generated from
//! `packages/protocol/dist/messages.js` (SHA-256 `bd22155340099ad027b9daa670139c91ab9cde626662526e0563077956b6cbe1`); the output
//! shapes are [`crate::creation_schema`].

use std::sync::LazyLock;

use crate::js_value::JsValue;
use crate::zod::{NumberCheck, Schema, Transform, UnknownKeys};

/// `CreationSnapshotSchema`.
#[must_use]
pub fn creation_snapshot() -> &'static Schema {
    &CREATION_SNAPSHOT
}

static SHARED_1: LazyLock<Schema> = LazyLock::new(|| {
    Schema::String(vec![])
});

static SHARED_2: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Discriminated(
        "type",
        vec![
            ("worktree_setup", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("worktree_setup".to_owned()),
                    ])),
                    ("worktreePath", Schema::String(vec![])),
                    ("branchName", Schema::String(vec![])),
                    ("log", Schema::String(vec![])),
                    ("commands", Schema::Array(Box::new(Schema::Object(
                        vec![
                            ("index", Schema::Number(vec![
                                NumberCheck::Int,
                                NumberCheck::Gt(0.0),
                            ])),
                            ("command", Schema::String(vec![])),
                            ("cwd", Schema::String(vec![])),
                            ("log", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::String(vec![])))), r#""""#)),
                            ("status", Schema::Enum(&["running", "completed", "failed"])),
                            ("exitCode", Schema::Nullable(Box::new(Schema::Number(vec![])))),
                            ("durationMs", Schema::Optional(Box::new(Schema::Number(vec![
                                NumberCheck::Gte(0.0),
                            ])))),
                        ],
                        UnknownKeys::Strip,
                    )))),
                    ("truncated", Schema::Optional(Box::new(Schema::Boolean))),
                ],
                UnknownKeys::Strip,
            )),
            ("shell", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("shell".to_owned()),
                    ])),
                    ("command", Schema::String(vec![])),
                    ("cwd", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("output", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("exitCode", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Number(vec![])))))),
                ],
                UnknownKeys::Strip,
            )),
            ("read", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("read".to_owned()),
                    ])),
                    ("filePath", Schema::String(vec![])),
                    ("content", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("offset", Schema::Optional(Box::new(Schema::Number(vec![])))),
                    ("limit", Schema::Optional(Box::new(Schema::Number(vec![])))),
                ],
                UnknownKeys::Strip,
            )),
            ("edit", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("edit".to_owned()),
                    ])),
                    ("filePath", Schema::String(vec![])),
                    ("oldString", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("newString", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("unifiedDiff", Schema::Optional(Box::new(Schema::String(vec![])))),
                ],
                UnknownKeys::Strip,
            )),
            ("write", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("write".to_owned()),
                    ])),
                    ("filePath", Schema::String(vec![])),
                    ("content", Schema::Optional(Box::new(Schema::String(vec![])))),
                ],
                UnknownKeys::Strip,
            )),
            ("search", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("search".to_owned()),
                    ])),
                    ("query", Schema::String(vec![])),
                    ("toolName", Schema::Optional(Box::new(Schema::Enum(&["search", "grep", "glob", "web_search"])))),
                    ("content", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("filePaths", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
                    ("webResults", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Object(
                        vec![
                            ("title", Schema::String(vec![])),
                            ("url", Schema::String(vec![])),
                        ],
                        UnknownKeys::Strip,
                    )))))),
                    ("annotations", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
                    ("numFiles", Schema::Optional(Box::new(Schema::Number(vec![])))),
                    ("numMatches", Schema::Optional(Box::new(Schema::Number(vec![])))),
                    ("durationMs", Schema::Optional(Box::new(Schema::Number(vec![])))),
                    ("durationSeconds", Schema::Optional(Box::new(Schema::Number(vec![])))),
                    ("truncated", Schema::Optional(Box::new(Schema::Boolean))),
                    ("mode", Schema::Optional(Box::new(Schema::Enum(&["content", "files_with_matches", "count"])))),
                ],
                UnknownKeys::Strip,
            )),
            ("fetch", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("fetch".to_owned()),
                    ])),
                    ("url", Schema::String(vec![])),
                    ("prompt", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("result", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("code", Schema::Optional(Box::new(Schema::Number(vec![])))),
                    ("codeText", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("bytes", Schema::Optional(Box::new(Schema::Number(vec![])))),
                    ("durationMs", Schema::Optional(Box::new(Schema::Number(vec![])))),
                ],
                UnknownKeys::Strip,
            )),
            ("sub_agent", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("sub_agent".to_owned()),
                    ])),
                    ("subAgentType", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("description", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("childSessionId", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("log", Schema::String(vec![])),
                    ("actions", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Object(
                        vec![
                            ("index", Schema::Number(vec![
                                NumberCheck::Int,
                                NumberCheck::Gt(0.0),
                            ])),
                            ("toolName", Schema::String(vec![])),
                            ("summary", Schema::Optional(Box::new(Schema::String(vec![])))),
                        ],
                        UnknownKeys::Strip,
                    )))))),
                ],
                UnknownKeys::Strip,
            )),
            ("plain_text", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("plain_text".to_owned()),
                    ])),
                    ("label", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("text", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("icon", Schema::Optional(Box::new(Schema::Enum(&["wrench", "square_terminal", "eye", "pencil", "search", "bot", "sparkles", "brain", "mic_vocal"])))),
                ],
                UnknownKeys::Strip,
            )),
            ("plan", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("plan".to_owned()),
                    ])),
                    ("text", Schema::String(vec![])),
                ],
                UnknownKeys::Strip,
            )),
            ("unknown", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("unknown".to_owned()),
                    ])),
                    ("input", Schema::Union(vec![
                        Schema::Null,
                        Schema::Boolean,
                        Schema::Number(vec![]),
                        Schema::String(vec![]),
                        Schema::Array(Box::new(Schema::Unknown)),
                        Schema::Object(
                            vec![],
                            UnknownKeys::Passthrough,
                        ),
                    ])),
                    ("output", Schema::Union(vec![
                        Schema::Null,
                        Schema::Boolean,
                        Schema::Number(vec![]),
                        Schema::String(vec![]),
                        Schema::Array(Box::new(Schema::Unknown)),
                        Schema::Object(
                            vec![],
                            UnknownKeys::Passthrough,
                        ),
                    ])),
                ],
                UnknownKeys::Strip,
            )),
        ],
    )
});

static CREATION_SNAPSHOT: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Object(
        vec![
            ("kind", Schema::Enum(&["workspace", "agent"])),
            ("idempotencyKey", Schema::String(vec![])),
            ("revision", Schema::Number(vec![
                NumberCheck::Int,
                NumberCheck::Gte(0.0),
            ])),
            ("phase", Schema::Enum(&["accepted", "workspace_ready", "agent_ready", "prompt_started", "completed", "failed"])),
            ("workspaceId", Schema::Nullable(Box::new(Schema::String(vec![])))),
            ("agentId", Schema::Nullable(Box::new(Schema::String(vec![])))),
            ("workspace", Schema::Optional(Box::new(Schema::Pipe(Box::new(Schema::Object(
                vec![
                    ("id", Schema::String(vec![])),
                    ("projectId", Schema::String(vec![])),
                    ("projectDisplayName", Schema::String(vec![])),
                    ("projectCustomName", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("projectCustomIconRevision", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("projectRootPath", Schema::String(vec![])),
                    ("workspaceDirectory", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("worktreeSlug", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("projectKind", Schema::Enum(&["git", "non_git", "directory"])),
                    ("workspaceKind", Schema::Enum(&["directory", "local_checkout", "checkout", "worktree"])),
                    ("name", Schema::String(vec![])),
                    ("title", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("pinnedAt", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("labels", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
                    ("archivingAt", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))), "null")),
                    ("status", Schema::Enum(&["needs_input", "failed", "running", "attention", "done"])),
                    ("statusEnteredAt", Schema::Pipe(Box::new(Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))), Box::new(Schema::Transform(Transform::NoIssue)))),
                    ("activityAt", Schema::Nullable(Box::new(Schema::String(vec![])))),
                    ("diffStat", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Object(
                        vec![
                            ("additions", Schema::Number(vec![])),
                            ("deletions", Schema::Number(vec![])),
                        ],
                        UnknownKeys::Strip,
                    )))))),
                    ("scripts", Schema::Default(Box::new(Schema::Array(Box::new(Schema::Object(
                        vec![
                            ("scriptName", Schema::String(vec![])),
                            ("type", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::Enum(&["script", "service"])))), r#""service""#)),
                            ("hostname", Schema::String(vec![])),
                            ("port", Schema::Nullable(Box::new(Schema::Number(vec![
                                NumberCheck::Int,
                                NumberCheck::Gt(0.0),
                            ])))),
                            ("localProxyUrl", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                            ("publicProxyUrl", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                            ("proxyUrl", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))), "null")),
                            ("lifecycle", Schema::Enum(&["running", "stopped"])),
                            ("health", Schema::Nullable(Box::new(Schema::Enum(&["healthy", "unhealthy"])))),
                            ("exitCode", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Number(vec![])))))), "null")),
                            ("terminalId", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))), "null")),
                        ],
                        UnknownKeys::Strip,
                    )))), "[]")),
                    ("gitRuntime", Schema::Nullable(Box::new(Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("currentBranch", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                            ("remoteUrl", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                            ("isPaseoOwnedWorktree", Schema::Optional(Box::new(Schema::Boolean))),
                            ("isDirty", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Boolean))))),
                            ("aheadBehind", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Object(
                                vec![
                                    ("ahead", Schema::Number(vec![])),
                                    ("behind", Schema::Number(vec![])),
                                ],
                                UnknownKeys::Strip,
                            )))))),
                            ("aheadOfOrigin", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Number(vec![])))))),
                            ("behindOfOrigin", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Number(vec![])))))),
                        ],
                        UnknownKeys::Strip,
                    )))))),
                    ("githubRuntime", Schema::Nullable(Box::new(Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("featuresEnabled", Schema::Optional(Box::new(Schema::Boolean))),
                            ("pullRequest", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Object(
                                vec![
                                    ("number", Schema::Optional(Box::new(Schema::Number(vec![])))),
                                    ("url", Schema::String(vec![])),
                                    ("title", Schema::String(vec![])),
                                    ("state", Schema::String(vec![])),
                                    ("baseRefName", Schema::String(vec![])),
                                    ("headRefName", Schema::String(vec![])),
                                    ("isMerged", Schema::Boolean),
                                    ("isDraft", Schema::Optional(Box::new(Schema::Boolean))),
                                    ("mergeable", Schema::Optional(Box::new(Schema::Catch(Box::new(Schema::Enum(&["MERGEABLE", "CONFLICTING", "UNKNOWN"])), r#""UNKNOWN""#)))),
                                    ("checks", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Object(
                                        vec![
                                            ("name", Schema::String(vec![])),
                                            ("status", Schema::Enum(&["success", "failure", "pending", "skipped", "cancelled"])),
                                            ("url", Schema::Nullable(Box::new(Schema::String(vec![])))),
                                            ("workflow", Schema::Optional(Box::new(Schema::String(vec![])))),
                                            ("duration", Schema::Optional(Box::new(Schema::String(vec![])))),
                                            ("traits", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
                                        ],
                                        UnknownKeys::Strip,
                                    )))))),
                                    ("checksStatus", Schema::Optional(Box::new(Schema::Enum(&["none", "pending", "success", "failure"])))),
                                    ("reviewDecision", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Enum(&["approved", "changes_requested", "pending"])))))),
                                    ("repoOwner", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("repoName", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("github", Schema::Optional(Box::new(Schema::Unknown))),
                                ],
                                UnknownKeys::Strip,
                            )))))),
                            ("error", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Object(
                                vec![
                                    ("message", Schema::String(vec![])),
                                ],
                                UnknownKeys::Strip,
                            )))))),
                            ("refreshedAt", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                        ],
                        UnknownKeys::Strip,
                    )))))),
                    ("forge", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("project", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("projectKey", Schema::String(vec![])),
                            ("projectName", Schema::String(vec![])),
                            ("workspaceName", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                            ("checkout", Schema::Union(vec![
                                Schema::Pipe(Box::new(Schema::Object(
                                    vec![
                                        ("cwd", Schema::String(vec![])),
                                        ("isGit", Schema::Literal(vec![
                                            JsValue::Bool(false),
                                        ])),
                                        ("currentBranch", Schema::Null),
                                        ("remoteUrl", Schema::Null),
                                        ("worktreeRoot", Schema::Optional(Box::new(Schema::Null))),
                                        ("isPaseoOwnedWorktree", Schema::Literal(vec![
                                            JsValue::Bool(false),
                                        ])),
                                        ("mainRepoRoot", Schema::Null),
                                    ],
                                    UnknownKeys::Strip,
                                )), Box::new(Schema::Transform(Transform::NoIssue))),
                                Schema::Pipe(Box::new(Schema::Object(
                                    vec![
                                        ("cwd", Schema::String(vec![])),
                                        ("isGit", Schema::Literal(vec![
                                            JsValue::Bool(true),
                                        ])),
                                        ("currentBranch", Schema::Nullable(Box::new(Schema::String(vec![])))),
                                        ("remoteUrl", Schema::Nullable(Box::new(Schema::String(vec![])))),
                                        ("worktreeRoot", Schema::Optional(Box::new(Schema::String(vec![])))),
                                        ("isPaseoOwnedWorktree", Schema::Literal(vec![
                                            JsValue::Bool(false),
                                        ])),
                                        ("mainRepoRoot", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))), "null")),
                                    ],
                                    UnknownKeys::Strip,
                                )), Box::new(Schema::Transform(Transform::NoIssue))),
                                Schema::Pipe(Box::new(Schema::Object(
                                    vec![
                                        ("cwd", Schema::String(vec![])),
                                        ("isGit", Schema::Literal(vec![
                                            JsValue::Bool(true),
                                        ])),
                                        ("currentBranch", Schema::Nullable(Box::new(Schema::String(vec![])))),
                                        ("remoteUrl", Schema::Nullable(Box::new(Schema::String(vec![])))),
                                        ("worktreeRoot", Schema::Optional(Box::new(Schema::String(vec![])))),
                                        ("isPaseoOwnedWorktree", Schema::Literal(vec![
                                            JsValue::Bool(true),
                                        ])),
                                        ("mainRepoRoot", Schema::String(vec![])),
                                    ],
                                    UnknownKeys::Strip,
                                )), Box::new(Schema::Transform(Transform::NoIssue))),
                            ])),
                        ],
                        UnknownKeys::Strip,
                    )))),
                    ("syncSeq", Schema::Optional(Box::new(Schema::Number(vec![
                        NumberCheck::Int,
                        NumberCheck::Gt(0.0),
                    ])))),
                ],
                UnknownKeys::Strip,
            )), Box::new(Schema::Transform(Transform::NoIssue)))))),
            ("agent", Schema::Optional(Box::new(Schema::Object(
                vec![
                    ("id", Schema::String(vec![])),
                    ("provider", Schema::Lazy(|| &SHARED_1)),
                    ("cwd", Schema::String(vec![])),
                    ("workspaceId", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("model", Schema::Nullable(Box::new(Schema::String(vec![])))),
                    ("features", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Discriminated(
                        "type",
                        vec![
                            ("toggle", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("toggle".to_owned()),
                                    ])),
                                    ("id", Schema::String(vec![])),
                                    ("label", Schema::String(vec![])),
                                    ("description", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("tooltip", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("icon", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("value", Schema::Boolean),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("select", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("select".to_owned()),
                                    ])),
                                    ("id", Schema::String(vec![])),
                                    ("label", Schema::String(vec![])),
                                    ("description", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("tooltip", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("icon", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("value", Schema::Nullable(Box::new(Schema::String(vec![])))),
                                    ("options", Schema::Array(Box::new(Schema::Object(
                                        vec![
                                            ("id", Schema::String(vec![])),
                                            ("label", Schema::String(vec![])),
                                            ("description", Schema::Optional(Box::new(Schema::String(vec![])))),
                                            ("isDefault", Schema::Optional(Box::new(Schema::Boolean))),
                                            ("metadata", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                ],
                                UnknownKeys::Strip,
                            )),
                        ],
                    )))))),
                    ("thinkingOptionId", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("effectiveThinkingOptionId", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("createdAt", Schema::String(vec![])),
                    ("updatedAt", Schema::String(vec![])),
                    ("lastUserMessageAt", Schema::Nullable(Box::new(Schema::String(vec![])))),
                    ("status", Schema::Enum(&["initializing", "idle", "running", "error", "closed"])),
                    ("activeTurn", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Object(
                        vec![
                            ("turnId", Schema::String(vec![])),
                            ("startedAt", Schema::Nullable(Box::new(Schema::String(vec![])))),
                        ],
                        UnknownKeys::Strip,
                    )))))),
                    ("capabilities", Schema::ObjectCatchall(
                        vec![
                            ("supportsStreaming", Schema::Boolean),
                            ("supportsSessionPersistence", Schema::Boolean),
                            ("supportsSessionListing", Schema::Optional(Box::new(Schema::Boolean))),
                            ("supportsDynamicModes", Schema::Boolean),
                            ("supportsMcpServers", Schema::Boolean),
                            ("supportsReasoningStream", Schema::Boolean),
                            ("supportsToolInvocations", Schema::Boolean),
                            ("supportsRewindConversation", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::Boolean))), "false")),
                            ("supportsRewindFiles", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::Boolean))), "false")),
                            ("supportsRewindBoth", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::Boolean))), "false")),
                        ],
                        Box::new(Schema::Boolean),
                    )),
                    ("currentModeId", Schema::Nullable(Box::new(Schema::String(vec![])))),
                    ("availableModes", Schema::Array(Box::new(Schema::Object(
                        vec![
                            ("id", Schema::String(vec![])),
                            ("label", Schema::String(vec![])),
                            ("description", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("icon", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("colorTier", Schema::Optional(Box::new(Schema::String(vec![])))),
                        ],
                        UnknownKeys::Strip,
                    )))),
                    ("pendingPermissions", Schema::Array(Box::new(Schema::Object(
                        vec![
                            ("id", Schema::String(vec![])),
                            ("provider", Schema::Lazy(|| &SHARED_1)),
                            ("name", Schema::String(vec![])),
                            ("kind", Schema::Enum(&["tool", "plan", "question", "mode", "other"])),
                            ("title", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("description", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("input", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))),
                            ("detail", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_2)))),
                            ("suggestions", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))))),
                            ("actions", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Object(
                                vec![
                                    ("id", Schema::String(vec![])),
                                    ("label", Schema::String(vec![])),
                                    ("behavior", Schema::Enum(&["allow", "deny"])),
                                    ("variant", Schema::Optional(Box::new(Schema::Enum(&["primary", "secondary", "danger"])))),
                                    ("intent", Schema::Optional(Box::new(Schema::Enum(&["implement", "implement_resume", "dismiss"])))),
                                ],
                                UnknownKeys::Strip,
                            )))))),
                            ("metadata", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))),
                        ],
                        UnknownKeys::Strip,
                    )))),
                    ("persistence", Schema::Nullable(Box::new(Schema::Nullable(Box::new(Schema::Object(
                        vec![
                            ("provider", Schema::Lazy(|| &SHARED_1)),
                            ("sessionId", Schema::String(vec![])),
                            ("nativeHandle", Schema::Optional(Box::new(Schema::String(vec![])))),
                            ("metadata", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))),
                        ],
                        UnknownKeys::Strip,
                    )))))),
                    ("runtimeInfo", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("provider", Schema::Lazy(|| &SHARED_1)),
                            ("sessionId", Schema::Nullable(Box::new(Schema::String(vec![])))),
                            ("model", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                            ("thinkingOptionId", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                            ("modeId", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                            ("extra", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))),
                        ],
                        UnknownKeys::Strip,
                    )))),
                    ("lastUsage", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("inputTokens", Schema::Optional(Box::new(Schema::Number(vec![])))),
                            ("cachedInputTokens", Schema::Optional(Box::new(Schema::Number(vec![])))),
                            ("outputTokens", Schema::Optional(Box::new(Schema::Number(vec![])))),
                            ("totalCostUsd", Schema::Optional(Box::new(Schema::Number(vec![])))),
                            ("contextWindowMaxTokens", Schema::Optional(Box::new(Schema::Number(vec![])))),
                            ("contextWindowUsedTokens", Schema::Optional(Box::new(Schema::Number(vec![])))),
                        ],
                        UnknownKeys::Strip,
                    )))),
                    ("lastError", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("title", Schema::Nullable(Box::new(Schema::String(vec![])))),
                    ("labels", Schema::Default(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::String(vec![])))), "{}")),
                    ("requiresAttention", Schema::Optional(Box::new(Schema::Boolean))),
                    ("attentionReason", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::Enum(&["finished", "error", "permission"])))))),
                    ("attentionTimestamp", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("archivedAt", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("providerUnavailable", Schema::Optional(Box::new(Schema::Boolean))),
                ],
                UnknownKeys::Strip,
            )))),
            ("error", Schema::Nullable(Box::new(Schema::String(vec![])))),
            ("setupSkippedReason", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("errorCode", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("failedStage", Schema::Optional(Box::new(Schema::Enum(&["workspace", "agent", "prompt"])))),
            ("outcomeUnknown", Schema::Optional(Box::new(Schema::Boolean))),
        ],
        UnknownKeys::Strip,
    )
});
