// Generated by scripts/phase3/creation-zod.mjs; do not edit.
//! `CreationSnapshotSchema` of pinned Paseo `5de45e2` as
//! [`crate::zod::output`] shapes, generated from
//! `packages/protocol/dist/messages.js` (SHA-256 `bd22155340099ad027b9daa670139c91ab9cde626662526e0563077956b6cbe1`).

use std::sync::LazyLock;

use crate::js_value::JsValue;
use crate::zod::output::{Catchall, NumberCheck, Shape, Transform};

/// SHA-256 of the `messages.js` this file was generated from.
pub const MESSAGES_JS_SHA256: &str = "bd22155340099ad027b9daa670139c91ab9cde626662526e0563077956b6cbe1";

/// `CreationSnapshotSchema`.
pub static CREATION_SNAPSHOT: LazyLock<Shape> = LazyLock::new(|| {
    Shape::Object(
        vec![
            ("kind", Shape::Enum(&["workspace", "agent"])),
            ("idempotencyKey", Shape::String),
            ("revision", Shape::Number(vec![
                NumberCheck::Int,
                NumberCheck::Gte(0.0),
            ])),
            ("phase", Shape::Enum(&["accepted", "workspace_ready", "agent_ready", "prompt_started", "completed", "failed"])),
            ("workspaceId", Shape::Nullable(Box::new(Shape::String))),
            ("agentId", Shape::Nullable(Box::new(Shape::String))),
            ("workspace", Shape::Optional(Box::new(Shape::Pipe(Box::new(Shape::Object(
                vec![
                    ("id", Shape::String),
                    ("projectId", Shape::String),
                    ("projectDisplayName", Shape::String),
                    ("projectCustomName", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                    ("projectCustomIconRevision", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                    ("projectRootPath", Shape::String),
                    ("workspaceDirectory", Shape::Optional(Box::new(Shape::String))),
                    ("worktreeSlug", Shape::Optional(Box::new(Shape::String))),
                    ("projectKind", Shape::Enum(&["git", "non_git", "directory"])),
                    ("workspaceKind", Shape::Enum(&["directory", "local_checkout", "checkout", "worktree"])),
                    ("name", Shape::String),
                    ("title", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                    ("pinnedAt", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                    ("labels", Shape::Optional(Box::new(Shape::Array(Box::new(Shape::String))))),
                    ("archivingAt", Shape::Default("null", Box::new(Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))))),
                    ("status", Shape::Enum(&["needs_input", "failed", "running", "attention", "done"])),
                    ("statusEnteredAt", Shape::Pipe(Box::new(Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))), Box::new(Shape::Transform(Transform::NullishToNull)))),
                    ("activityAt", Shape::Nullable(Box::new(Shape::String))),
                    ("diffStat", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Object(
                        vec![
                            ("additions", Shape::Number(vec![])),
                            ("deletions", Shape::Number(vec![])),
                        ],
                        Catchall::Strip,
                    )))))),
                    ("scripts", Shape::Default("[]", Box::new(Shape::Array(Box::new(Shape::Object(
                        vec![
                            ("scriptName", Shape::String),
                            ("type", Shape::Default(r#""service""#, Box::new(Shape::Optional(Box::new(Shape::Enum(&["script", "service"])))))),
                            ("hostname", Shape::String),
                            ("port", Shape::Nullable(Box::new(Shape::Number(vec![
                                NumberCheck::Int,
                                NumberCheck::Gt(0.0),
                            ])))),
                            ("localProxyUrl", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                            ("publicProxyUrl", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                            ("proxyUrl", Shape::Default("null", Box::new(Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))))),
                            ("lifecycle", Shape::Enum(&["running", "stopped"])),
                            ("health", Shape::Nullable(Box::new(Shape::Enum(&["healthy", "unhealthy"])))),
                            ("exitCode", Shape::Default("null", Box::new(Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Number(vec![])))))))),
                            ("terminalId", Shape::Default("null", Box::new(Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))))),
                        ],
                        Catchall::Strip,
                    )))))),
                    ("gitRuntime", Shape::Nullable(Box::new(Shape::Optional(Box::new(Shape::Object(
                        vec![
                            ("currentBranch", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                            ("remoteUrl", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                            ("isPaseoOwnedWorktree", Shape::Optional(Box::new(Shape::Boolean))),
                            ("isDirty", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Boolean))))),
                            ("aheadBehind", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Object(
                                vec![
                                    ("ahead", Shape::Number(vec![])),
                                    ("behind", Shape::Number(vec![])),
                                ],
                                Catchall::Strip,
                            )))))),
                            ("aheadOfOrigin", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Number(vec![])))))),
                            ("behindOfOrigin", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Number(vec![])))))),
                        ],
                        Catchall::Strip,
                    )))))),
                    ("githubRuntime", Shape::Nullable(Box::new(Shape::Optional(Box::new(Shape::Object(
                        vec![
                            ("featuresEnabled", Shape::Optional(Box::new(Shape::Boolean))),
                            ("pullRequest", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Object(
                                vec![
                                    ("number", Shape::Optional(Box::new(Shape::Number(vec![])))),
                                    ("url", Shape::String),
                                    ("title", Shape::String),
                                    ("state", Shape::String),
                                    ("baseRefName", Shape::String),
                                    ("headRefName", Shape::String),
                                    ("isMerged", Shape::Boolean),
                                    ("isDraft", Shape::Optional(Box::new(Shape::Boolean))),
                                    ("mergeable", Shape::Optional(Box::new(Shape::Catch(r#""UNKNOWN""#, Box::new(Shape::Enum(&["MERGEABLE", "CONFLICTING", "UNKNOWN"])))))),
                                    ("checks", Shape::Optional(Box::new(Shape::Array(Box::new(Shape::Object(
                                        vec![
                                            ("name", Shape::String),
                                            ("status", Shape::Enum(&["success", "failure", "pending", "skipped", "cancelled"])),
                                            ("url", Shape::Nullable(Box::new(Shape::String))),
                                            ("workflow", Shape::Optional(Box::new(Shape::String))),
                                            ("duration", Shape::Optional(Box::new(Shape::String))),
                                            ("traits", Shape::Optional(Box::new(Shape::Array(Box::new(Shape::String))))),
                                        ],
                                        Catchall::Strip,
                                    )))))),
                                    ("checksStatus", Shape::Optional(Box::new(Shape::Enum(&["none", "pending", "success", "failure"])))),
                                    ("reviewDecision", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Enum(&["approved", "changes_requested", "pending"])))))),
                                    ("repoOwner", Shape::Optional(Box::new(Shape::String))),
                                    ("repoName", Shape::Optional(Box::new(Shape::String))),
                                    ("github", Shape::Optional(Box::new(Shape::Unknown))),
                                ],
                                Catchall::Strip,
                            )))))),
                            ("error", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Object(
                                vec![
                                    ("message", Shape::String),
                                ],
                                Catchall::Strip,
                            )))))),
                            ("refreshedAt", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                        ],
                        Catchall::Strip,
                    )))))),
                    ("forge", Shape::Optional(Box::new(Shape::String))),
                    ("project", Shape::Optional(Box::new(Shape::Object(
                        vec![
                            ("projectKey", Shape::String),
                            ("projectName", Shape::String),
                            ("workspaceName", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                            ("checkout", Shape::Union(vec![
                                Shape::Pipe(Box::new(Shape::Object(
                                    vec![
                                        ("cwd", Shape::String),
                                        ("isGit", Shape::Literal(vec![
                                            JsValue::Bool(false),
                                        ])),
                                        ("currentBranch", Shape::Null),
                                        ("remoteUrl", Shape::Null),
                                        ("worktreeRoot", Shape::Optional(Box::new(Shape::Null))),
                                        ("isPaseoOwnedWorktree", Shape::Literal(vec![
                                            JsValue::Bool(false),
                                        ])),
                                        ("mainRepoRoot", Shape::Null),
                                    ],
                                    Catchall::Strip,
                                )), Box::new(Shape::Transform(Transform::SetNull("worktreeRoot")))),
                                Shape::Pipe(Box::new(Shape::Object(
                                    vec![
                                        ("cwd", Shape::String),
                                        ("isGit", Shape::Literal(vec![
                                            JsValue::Bool(true),
                                        ])),
                                        ("currentBranch", Shape::Nullable(Box::new(Shape::String))),
                                        ("remoteUrl", Shape::Nullable(Box::new(Shape::String))),
                                        ("worktreeRoot", Shape::Optional(Box::new(Shape::String))),
                                        ("isPaseoOwnedWorktree", Shape::Literal(vec![
                                            JsValue::Bool(false),
                                        ])),
                                        ("mainRepoRoot", Shape::Default("null", Box::new(Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))))),
                                    ],
                                    Catchall::Strip,
                                )), Box::new(Shape::Transform(Transform::SetOrFallback("worktreeRoot", "cwd")))),
                                Shape::Pipe(Box::new(Shape::Object(
                                    vec![
                                        ("cwd", Shape::String),
                                        ("isGit", Shape::Literal(vec![
                                            JsValue::Bool(true),
                                        ])),
                                        ("currentBranch", Shape::Nullable(Box::new(Shape::String))),
                                        ("remoteUrl", Shape::Nullable(Box::new(Shape::String))),
                                        ("worktreeRoot", Shape::Optional(Box::new(Shape::String))),
                                        ("isPaseoOwnedWorktree", Shape::Literal(vec![
                                            JsValue::Bool(true),
                                        ])),
                                        ("mainRepoRoot", Shape::String),
                                    ],
                                    Catchall::Strip,
                                )), Box::new(Shape::Transform(Transform::SetOrFallback("worktreeRoot", "cwd")))),
                            ])),
                        ],
                        Catchall::Strip,
                    )))),
                    ("syncSeq", Shape::Optional(Box::new(Shape::Number(vec![
                        NumberCheck::Int,
                        NumberCheck::Gt(0.0),
                    ])))),
                ],
                Catchall::Strip,
            )), Box::new(Shape::Transform(Transform::SetOrFallback("workspaceDirectory", "projectRootPath"))))))),
            ("agent", Shape::Optional(Box::new(Shape::Object(
                vec![
                    ("id", Shape::String),
                    ("provider", Shape::String),
                    ("cwd", Shape::String),
                    ("workspaceId", Shape::Optional(Box::new(Shape::String))),
                    ("model", Shape::Nullable(Box::new(Shape::String))),
                    ("features", Shape::Optional(Box::new(Shape::Array(Box::new(Shape::Discriminated(
                        "type",
                        vec![
                            ("toggle", Shape::Object(
                                vec![
                                    ("type", Shape::Literal(vec![
                                        JsValue::String("toggle".to_owned()),
                                    ])),
                                    ("id", Shape::String),
                                    ("label", Shape::String),
                                    ("description", Shape::Optional(Box::new(Shape::String))),
                                    ("tooltip", Shape::Optional(Box::new(Shape::String))),
                                    ("icon", Shape::Optional(Box::new(Shape::String))),
                                    ("value", Shape::Boolean),
                                ],
                                Catchall::Strip,
                            )),
                            ("select", Shape::Object(
                                vec![
                                    ("type", Shape::Literal(vec![
                                        JsValue::String("select".to_owned()),
                                    ])),
                                    ("id", Shape::String),
                                    ("label", Shape::String),
                                    ("description", Shape::Optional(Box::new(Shape::String))),
                                    ("tooltip", Shape::Optional(Box::new(Shape::String))),
                                    ("icon", Shape::Optional(Box::new(Shape::String))),
                                    ("value", Shape::Nullable(Box::new(Shape::String))),
                                    ("options", Shape::Array(Box::new(Shape::Object(
                                        vec![
                                            ("id", Shape::String),
                                            ("label", Shape::String),
                                            ("description", Shape::Optional(Box::new(Shape::String))),
                                            ("isDefault", Shape::Optional(Box::new(Shape::Boolean))),
                                            ("metadata", Shape::Optional(Box::new(Shape::Record(Box::new(Shape::Unknown))))),
                                        ],
                                        Catchall::Strip,
                                    )))),
                                ],
                                Catchall::Strip,
                            )),
                        ],
                    )))))),
                    ("thinkingOptionId", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                    ("effectiveThinkingOptionId", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                    ("createdAt", Shape::String),
                    ("updatedAt", Shape::String),
                    ("lastUserMessageAt", Shape::Nullable(Box::new(Shape::String))),
                    ("status", Shape::Enum(&["initializing", "idle", "running", "error", "closed"])),
                    ("activeTurn", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Object(
                        vec![
                            ("turnId", Shape::String),
                            ("startedAt", Shape::Nullable(Box::new(Shape::String))),
                        ],
                        Catchall::Strip,
                    )))))),
                    ("capabilities", Shape::Object(
                        vec![
                            ("supportsStreaming", Shape::Boolean),
                            ("supportsSessionPersistence", Shape::Boolean),
                            ("supportsSessionListing", Shape::Optional(Box::new(Shape::Boolean))),
                            ("supportsDynamicModes", Shape::Boolean),
                            ("supportsMcpServers", Shape::Boolean),
                            ("supportsReasoningStream", Shape::Boolean),
                            ("supportsToolInvocations", Shape::Boolean),
                            ("supportsRewindConversation", Shape::Default("false", Box::new(Shape::Optional(Box::new(Shape::Boolean))))),
                            ("supportsRewindFiles", Shape::Default("false", Box::new(Shape::Optional(Box::new(Shape::Boolean))))),
                            ("supportsRewindBoth", Shape::Default("false", Box::new(Shape::Optional(Box::new(Shape::Boolean))))),
                        ],
                        Catchall::Keep(Box::new(Shape::Boolean)),
                    )),
                    ("currentModeId", Shape::Nullable(Box::new(Shape::String))),
                    ("availableModes", Shape::Array(Box::new(Shape::Object(
                        vec![
                            ("id", Shape::String),
                            ("label", Shape::String),
                            ("description", Shape::Optional(Box::new(Shape::String))),
                            ("icon", Shape::Optional(Box::new(Shape::String))),
                            ("colorTier", Shape::Optional(Box::new(Shape::String))),
                        ],
                        Catchall::Strip,
                    )))),
                    ("pendingPermissions", Shape::Array(Box::new(Shape::Object(
                        vec![
                            ("id", Shape::String),
                            ("provider", Shape::String),
                            ("name", Shape::String),
                            ("kind", Shape::Enum(&["tool", "plan", "question", "mode", "other"])),
                            ("title", Shape::Optional(Box::new(Shape::String))),
                            ("description", Shape::Optional(Box::new(Shape::String))),
                            ("input", Shape::Optional(Box::new(Shape::Record(Box::new(Shape::Unknown))))),
                            ("detail", Shape::Optional(Box::new(Shape::Lazy(|| &SHARED_0)))),
                            ("suggestions", Shape::Optional(Box::new(Shape::Array(Box::new(Shape::Record(Box::new(Shape::Unknown))))))),
                            ("actions", Shape::Optional(Box::new(Shape::Array(Box::new(Shape::Object(
                                vec![
                                    ("id", Shape::String),
                                    ("label", Shape::String),
                                    ("behavior", Shape::Enum(&["allow", "deny"])),
                                    ("variant", Shape::Optional(Box::new(Shape::Enum(&["primary", "secondary", "danger"])))),
                                    ("intent", Shape::Optional(Box::new(Shape::Enum(&["implement", "implement_resume", "dismiss"])))),
                                ],
                                Catchall::Strip,
                            )))))),
                            ("metadata", Shape::Optional(Box::new(Shape::Record(Box::new(Shape::Unknown))))),
                        ],
                        Catchall::Strip,
                    )))),
                    ("persistence", Shape::Nullable(Box::new(Shape::Nullable(Box::new(Shape::Object(
                        vec![
                            ("provider", Shape::String),
                            ("sessionId", Shape::String),
                            ("nativeHandle", Shape::Optional(Box::new(Shape::String))),
                            ("metadata", Shape::Optional(Box::new(Shape::Record(Box::new(Shape::Unknown))))),
                        ],
                        Catchall::Strip,
                    )))))),
                    ("runtimeInfo", Shape::Optional(Box::new(Shape::Object(
                        vec![
                            ("provider", Shape::String),
                            ("sessionId", Shape::Nullable(Box::new(Shape::String))),
                            ("model", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                            ("thinkingOptionId", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                            ("modeId", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                            ("extra", Shape::Optional(Box::new(Shape::Record(Box::new(Shape::Unknown))))),
                        ],
                        Catchall::Strip,
                    )))),
                    ("lastUsage", Shape::Optional(Box::new(Shape::Object(
                        vec![
                            ("inputTokens", Shape::Optional(Box::new(Shape::Number(vec![])))),
                            ("cachedInputTokens", Shape::Optional(Box::new(Shape::Number(vec![])))),
                            ("outputTokens", Shape::Optional(Box::new(Shape::Number(vec![])))),
                            ("totalCostUsd", Shape::Optional(Box::new(Shape::Number(vec![])))),
                            ("contextWindowMaxTokens", Shape::Optional(Box::new(Shape::Number(vec![])))),
                            ("contextWindowUsedTokens", Shape::Optional(Box::new(Shape::Number(vec![])))),
                        ],
                        Catchall::Strip,
                    )))),
                    ("lastError", Shape::Optional(Box::new(Shape::String))),
                    ("title", Shape::Nullable(Box::new(Shape::String))),
                    ("labels", Shape::Default("{}", Box::new(Shape::Record(Box::new(Shape::String))))),
                    ("requiresAttention", Shape::Optional(Box::new(Shape::Boolean))),
                    ("attentionReason", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Enum(&["finished", "error", "permission"])))))),
                    ("attentionTimestamp", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                    ("archivedAt", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::String))))),
                    ("providerUnavailable", Shape::Optional(Box::new(Shape::Boolean))),
                ],
                Catchall::Strip,
            )))),
            ("error", Shape::Nullable(Box::new(Shape::String))),
            ("setupSkippedReason", Shape::Optional(Box::new(Shape::String))),
            ("errorCode", Shape::Optional(Box::new(Shape::String))),
            ("failedStage", Shape::Optional(Box::new(Shape::Enum(&["workspace", "agent", "prompt"])))),
            ("outcomeUnknown", Shape::Optional(Box::new(Shape::Boolean))),
        ],
        Catchall::Strip,
    )
});

static SHARED_0: LazyLock<Shape> = LazyLock::new(|| {
    Shape::Discriminated(
        "type",
        vec![
            ("worktree_setup", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("worktree_setup".to_owned()),
                    ])),
                    ("worktreePath", Shape::String),
                    ("branchName", Shape::String),
                    ("log", Shape::String),
                    ("commands", Shape::Array(Box::new(Shape::Object(
                        vec![
                            ("index", Shape::Number(vec![
                                NumberCheck::Int,
                                NumberCheck::Gt(0.0),
                            ])),
                            ("command", Shape::String),
                            ("cwd", Shape::String),
                            ("log", Shape::Default(r#""""#, Box::new(Shape::Optional(Box::new(Shape::String))))),
                            ("status", Shape::Enum(&["running", "completed", "failed"])),
                            ("exitCode", Shape::Nullable(Box::new(Shape::Number(vec![])))),
                            ("durationMs", Shape::Optional(Box::new(Shape::Number(vec![
                                NumberCheck::Gte(0.0),
                            ])))),
                        ],
                        Catchall::Strip,
                    )))),
                    ("truncated", Shape::Optional(Box::new(Shape::Boolean))),
                ],
                Catchall::Strip,
            )),
            ("shell", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("shell".to_owned()),
                    ])),
                    ("command", Shape::String),
                    ("cwd", Shape::Optional(Box::new(Shape::String))),
                    ("output", Shape::Optional(Box::new(Shape::String))),
                    ("exitCode", Shape::Optional(Box::new(Shape::Nullable(Box::new(Shape::Number(vec![])))))),
                ],
                Catchall::Strip,
            )),
            ("read", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("read".to_owned()),
                    ])),
                    ("filePath", Shape::String),
                    ("content", Shape::Optional(Box::new(Shape::String))),
                    ("offset", Shape::Optional(Box::new(Shape::Number(vec![])))),
                    ("limit", Shape::Optional(Box::new(Shape::Number(vec![])))),
                ],
                Catchall::Strip,
            )),
            ("edit", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("edit".to_owned()),
                    ])),
                    ("filePath", Shape::String),
                    ("oldString", Shape::Optional(Box::new(Shape::String))),
                    ("newString", Shape::Optional(Box::new(Shape::String))),
                    ("unifiedDiff", Shape::Optional(Box::new(Shape::String))),
                ],
                Catchall::Strip,
            )),
            ("write", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("write".to_owned()),
                    ])),
                    ("filePath", Shape::String),
                    ("content", Shape::Optional(Box::new(Shape::String))),
                ],
                Catchall::Strip,
            )),
            ("search", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("search".to_owned()),
                    ])),
                    ("query", Shape::String),
                    ("toolName", Shape::Optional(Box::new(Shape::Enum(&["search", "grep", "glob", "web_search"])))),
                    ("content", Shape::Optional(Box::new(Shape::String))),
                    ("filePaths", Shape::Optional(Box::new(Shape::Array(Box::new(Shape::String))))),
                    ("webResults", Shape::Optional(Box::new(Shape::Array(Box::new(Shape::Object(
                        vec![
                            ("title", Shape::String),
                            ("url", Shape::String),
                        ],
                        Catchall::Strip,
                    )))))),
                    ("annotations", Shape::Optional(Box::new(Shape::Array(Box::new(Shape::String))))),
                    ("numFiles", Shape::Optional(Box::new(Shape::Number(vec![])))),
                    ("numMatches", Shape::Optional(Box::new(Shape::Number(vec![])))),
                    ("durationMs", Shape::Optional(Box::new(Shape::Number(vec![])))),
                    ("durationSeconds", Shape::Optional(Box::new(Shape::Number(vec![])))),
                    ("truncated", Shape::Optional(Box::new(Shape::Boolean))),
                    ("mode", Shape::Optional(Box::new(Shape::Enum(&["content", "files_with_matches", "count"])))),
                ],
                Catchall::Strip,
            )),
            ("fetch", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("fetch".to_owned()),
                    ])),
                    ("url", Shape::String),
                    ("prompt", Shape::Optional(Box::new(Shape::String))),
                    ("result", Shape::Optional(Box::new(Shape::String))),
                    ("code", Shape::Optional(Box::new(Shape::Number(vec![])))),
                    ("codeText", Shape::Optional(Box::new(Shape::String))),
                    ("bytes", Shape::Optional(Box::new(Shape::Number(vec![])))),
                    ("durationMs", Shape::Optional(Box::new(Shape::Number(vec![])))),
                ],
                Catchall::Strip,
            )),
            ("sub_agent", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("sub_agent".to_owned()),
                    ])),
                    ("subAgentType", Shape::Optional(Box::new(Shape::String))),
                    ("description", Shape::Optional(Box::new(Shape::String))),
                    ("childSessionId", Shape::Optional(Box::new(Shape::String))),
                    ("log", Shape::String),
                    ("actions", Shape::Optional(Box::new(Shape::Array(Box::new(Shape::Object(
                        vec![
                            ("index", Shape::Number(vec![
                                NumberCheck::Int,
                                NumberCheck::Gt(0.0),
                            ])),
                            ("toolName", Shape::String),
                            ("summary", Shape::Optional(Box::new(Shape::String))),
                        ],
                        Catchall::Strip,
                    )))))),
                ],
                Catchall::Strip,
            )),
            ("plain_text", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("plain_text".to_owned()),
                    ])),
                    ("label", Shape::Optional(Box::new(Shape::String))),
                    ("text", Shape::Optional(Box::new(Shape::String))),
                    ("icon", Shape::Optional(Box::new(Shape::Enum(&["wrench", "square_terminal", "eye", "pencil", "search", "bot", "sparkles", "brain", "mic_vocal"])))),
                ],
                Catchall::Strip,
            )),
            ("plan", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("plan".to_owned()),
                    ])),
                    ("text", Shape::String),
                ],
                Catchall::Strip,
            )),
            ("unknown", Shape::Object(
                vec![
                    ("type", Shape::Literal(vec![
                        JsValue::String("unknown".to_owned()),
                    ])),
                    ("input", Shape::Union(vec![
                        Shape::Null,
                        Shape::Boolean,
                        Shape::Number(vec![]),
                        Shape::String,
                        Shape::Array(Box::new(Shape::Unknown)),
                        Shape::Object(
                            vec![],
                            Catchall::Keep(Box::new(Shape::Unknown)),
                        ),
                    ])),
                    ("output", Shape::Union(vec![
                        Shape::Null,
                        Shape::Boolean,
                        Shape::Number(vec![]),
                        Shape::String,
                        Shape::Array(Box::new(Shape::Unknown)),
                        Shape::Object(
                            vec![],
                            Catchall::Keep(Box::new(Shape::Unknown)),
                        ),
                    ])),
                ],
                Catchall::Strip,
            )),
        ],
    )
});
