// Generated by scripts/phase3/contracts-zod.mjs; do not edit.
//! `WSInboundMessageSchema` of pinned Paseo `5de45e2` as [`crate::zod`]
//! schemas, generated from `packages/protocol/dist/messages.js`
//! (SHA-256 `bd22155340099ad027b9daa670139c91ab9cde626662526e0563077956b6cbe1`).
//!
//! Session request types without a Rust model are [`Schema::Unmodeled`].

use std::sync::LazyLock;

use crate::js_value::JsValue;
use crate::zod::{NumberCheck, Outcome, Schema, StringCheck, Transform, UnknownKeys, check};

/// SHA-256 of the `messages.js` this file was generated from.
pub const MESSAGES_JS_SHA256: &str = "bd22155340099ad027b9daa670139c91ab9cde626662526e0563077956b6cbe1";

/// Runs `WSInboundMessageSchema.safeParse(value)`.
#[must_use]
pub fn check_inbound(value: &JsValue) -> Outcome {
    check(&WS_INBOUND_MESSAGE, value)
}

static WS_INBOUND_MESSAGE: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Discriminated(
        "type",
        vec![
            ("ping", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("ping".to_owned()),
                    ])),
                ],
                UnknownKeys::Strip,
            )),
            ("hello", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("hello".to_owned()),
                    ])),
                    ("clientId", Schema::String(vec![
                        StringCheck::Min(1),
                    ])),
                    ("clientType", Schema::Enum(&["mobile", "browser", "cli", "mcp", "hub"])),
                    ("protocolVersion", Schema::Number(vec![
                        NumberCheck::Int,
                    ])),
                    ("auth", Schema::Optional(Box::new(Schema::Discriminated(
                        "kind",
                        vec![
                            ("password", Schema::Object(
                                vec![
                                    ("kind", Schema::Literal(vec![
                                        JsValue::String("password".to_owned()),
                                    ])),
                                    ("password", Schema::String(vec![])),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("localCredential", Schema::Object(
                                vec![
                                    ("kind", Schema::Literal(vec![
                                        JsValue::String("localCredential".to_owned()),
                                    ])),
                                    ("token", Schema::String(vec![])),
                                ],
                                UnknownKeys::Strip,
                            )),
                        ],
                    )))),
                    ("appVersion", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("capabilities", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("voice", Schema::Optional(Box::new(Schema::Boolean))),
                            ("hello_rejection", Schema::Optional(Box::new(Schema::Boolean))),
                            ("pushNotifications", Schema::Optional(Box::new(Schema::Boolean))),
                            ("explicit_event_subscriptions", Schema::Optional(Box::new(Schema::Boolean))),
                            ("all_providers", Schema::Optional(Box::new(Schema::Boolean))),
                            ("reasoning_merge_enum", Schema::Optional(Box::new(Schema::Boolean))),
                            ("selective_agent_timeline", Schema::Optional(Box::new(Schema::Boolean))),
                            ("custom_mode_icons", Schema::Optional(Box::new(Schema::Boolean))),
                            ("terminal_reflowable_snapshot", Schema::Optional(Box::new(Schema::Boolean))),
                            ("provider_subagents", Schema::Optional(Box::new(Schema::Boolean))),
                            ("project_updates", Schema::Optional(Box::new(Schema::Boolean))),
                            ("compact_provider_snapshots", Schema::Optional(Box::new(Schema::Boolean))),
                            ("provider_snapshot_references", Schema::Optional(Box::new(Schema::Boolean))),
                            ("timeline_replacement_invalidation", Schema::Optional(Box::new(Schema::Boolean))),
                            ("timeline_notifications", Schema::Optional(Box::new(Schema::Boolean))),
                            ("browser_host", Schema::Optional(Box::new(Schema::Object(
                                vec![
                                    ("supportedCommands", Schema::Pipe(Box::new(Schema::Array(Box::new(Schema::String(vec![
                                        StringCheck::Min(1),
                                    ])))), Box::new(Schema::Transform(Transform::BrowserHostCommands)))),
                                    ("hostKind", Schema::Default(Box::new(Schema::String(vec![
                                        StringCheck::Min(1),
                                    ])), r#""browser host""#)),
                                ],
                                UnknownKeys::Passthrough,
                            )))),
                        ],
                        UnknownKeys::Passthrough,
                    )))),
                ],
                UnknownKeys::Strip,
            )),
            ("recording_state", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("recording_state".to_owned()),
                    ])),
                    ("isRecording", Schema::Boolean),
                ],
                UnknownKeys::Strip,
            )),
            ("session", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("session".to_owned()),
                    ])),
                    ("message", Schema::Discriminated(
                        "type",
                        vec![
                            ("browser.host.register.request", Schema::Unmodeled),
                            ("subscription.release.request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("subscription.release.request".to_owned()),
                                    ])),
                                    ("requestId", Schema::String(vec![])),
                                    ("subscriptionId", Schema::String(vec![])),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("session.events.set_subscription.request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("session.events.set_subscription.request".to_owned()),
                                    ])),
                                    ("requestId", Schema::String(vec![])),
                                    ("events", Schema::Array(Box::new(Schema::Enum(&["project.update", "providers_snapshot_update", "agent_attention_required", "agent_permission_request", "agent_permission_resolved", "checkout_status_update", "script_status_update", "workspace_setup_progress", "agent.provider_subagents.update", "terminal_attention_required", "status.server_info", "status.daemon_config_changed", "status.plugin_catalog_changed", "status.plugin_settings_changed", "activity_log", "hub.execution.agent.update", "hub.execution.agent.stream"])))),
                                    ("notifications", Schema::Optional(Box::new(Schema::Boolean))),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("hub.execution.agent.create.request", Schema::Unmodeled),
                            ("hub.execution.agent.validate.request", Schema::Unmodeled),
                            ("hub.execution.control.request", Schema::Unmodeled),
                            ("browser.automation.execute.response", Schema::Unmodeled),
                            ("voice_audio_chunk", Schema::Unmodeled),
                            ("abort_request", Schema::Unmodeled),
                            ("audio_played", Schema::Unmodeled),
                            ("fetch_agents_request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("fetch_agents_request".to_owned()),
                                    ])),
                                    ("requestId", Schema::String(vec![])),
                                    ("scope", Schema::Optional(Box::new(Schema::Enum(&["active"])))),
                                    ("filter", Schema::Optional(Box::new(Schema::Object(
                                        vec![
                                            ("labels", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::String(vec![])))))),
                                            ("projectKeys", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
                                            ("statuses", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Enum(&["initializing", "idle", "running", "error", "closed"])))))),
                                            ("includeArchived", Schema::Optional(Box::new(Schema::Boolean))),
                                            ("requiresAttention", Schema::Optional(Box::new(Schema::Boolean))),
                                            ("thinkingOptionId", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("sort", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Object(
                                        vec![
                                            ("key", Schema::Enum(&["status_priority", "created_at", "updated_at", "title"])),
                                            ("direction", Schema::Enum(&["asc", "desc"])),
                                        ],
                                        UnknownKeys::Strip,
                                    )))))),
                                    ("page", Schema::Optional(Box::new(Schema::Object(
                                        vec![
                                            ("limit", Schema::Number(vec![
                                                NumberCheck::Int,
                                                NumberCheck::Gt(0.0),
                                                NumberCheck::Lte(200.0),
                                            ])),
                                            ("cursor", Schema::Optional(Box::new(Schema::String(vec![
                                                StringCheck::Min(1),
                                            ])))),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("subscribe", Schema::Optional(Box::new(Schema::Object(
                                        vec![
                                            ("subscriptionId", Schema::Optional(Box::new(Schema::String(vec![])))),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("sync", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_0)))),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("fetch_agent_history_request", Schema::Unmodeled),
                            ("fetch_recent_provider_sessions_request", Schema::Unmodeled),
                            ("fetch_workspaces_request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("fetch_workspaces_request".to_owned()),
                                    ])),
                                    ("requestId", Schema::String(vec![])),
                                    ("filter", Schema::Optional(Box::new(Schema::Object(
                                        vec![
                                            ("query", Schema::Optional(Box::new(Schema::String(vec![])))),
                                            ("projectId", Schema::Optional(Box::new(Schema::String(vec![])))),
                                            ("idPrefix", Schema::Optional(Box::new(Schema::String(vec![])))),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("sort", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Object(
                                        vec![
                                            ("key", Schema::Enum(&["status_priority", "activity_at", "name", "project_id"])),
                                            ("direction", Schema::Enum(&["asc", "desc"])),
                                        ],
                                        UnknownKeys::Strip,
                                    )))))),
                                    ("page", Schema::Optional(Box::new(Schema::Object(
                                        vec![
                                            ("limit", Schema::Number(vec![
                                                NumberCheck::Int,
                                                NumberCheck::Gt(0.0),
                                                NumberCheck::Lte(200.0),
                                            ])),
                                            ("cursor", Schema::Optional(Box::new(Schema::String(vec![
                                                StringCheck::Min(1),
                                            ])))),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("subscribe", Schema::Optional(Box::new(Schema::Object(
                                        vec![
                                            ("subscriptionId", Schema::Optional(Box::new(Schema::String(vec![])))),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("sync", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_0)))),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("project.list.request", Schema::Unmodeled),
                            ("fetch_agent_request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("fetch_agent_request".to_owned()),
                                    ])),
                                    ("requestId", Schema::String(vec![])),
                                    ("agentId", Schema::String(vec![])),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("delete_agent_request", Schema::Unmodeled),
                            ("archive_agent_request", Schema::Unmodeled),
                            ("close_items_request", Schema::Unmodeled),
                            ("update_agent_request", Schema::Unmodeled),
                            ("project.rename.request", Schema::Unmodeled),
                            ("project.icon.set.request", Schema::Unmodeled),
                            ("project.remove.request", Schema::Unmodeled),
                            ("workspace.title.set.request", Schema::Unmodeled),
                            ("workspace.pin.set.request", Schema::Unmodeled),
                            ("workspace.label.list.request", Schema::Unmodeled),
                            ("workspace.label.assignment.set.request", Schema::Unmodeled),
                            ("workspace.label.update.request", Schema::Unmodeled),
                            ("workspace.label.delete.request", Schema::Unmodeled),
                            ("workspace.label.delete.inspect.request", Schema::Unmodeled),
                            ("workspace.recovery.inspect.request", Schema::Unmodeled),
                            ("workspace.recovery.restore.request", Schema::Unmodeled),
                            ("set_voice_mode", Schema::Unmodeled),
                            ("send_agent_message_request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("send_agent_message_request".to_owned()),
                                    ])),
                                    ("requestId", Schema::String(vec![])),
                                    ("agentId", Schema::String(vec![])),
                                    ("text", Schema::String(vec![])),
                                    ("messageId", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("activeTurnBehavior", Schema::Optional(Box::new(Schema::Enum(&["interrupt", "steer"])))),
                                    ("images", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Lazy(|| &SHARED_1)))))),
                                    ("attachments", Schema::Lazy(|| &SHARED_2)),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("wait_for_finish_request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("wait_for_finish_request".to_owned()),
                                    ])),
                                    ("requestId", Schema::String(vec![])),
                                    ("agentId", Schema::String(vec![])),
                                    ("timeoutMs", Schema::Optional(Box::new(Schema::Number(vec![
                                        NumberCheck::Int,
                                        NumberCheck::Gt(0.0),
                                    ])))),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("daemon.get_status.request", Schema::Unmodeled),
                            ("daemon.get_pairing_offer.request", Schema::Unmodeled),
                            ("daemon.config.reload.request", Schema::Unmodeled),
                            ("hub.management.daemon.connect.request", Schema::Unmodeled),
                            ("hub.management.daemon.get_status.request", Schema::Unmodeled),
                            ("hub.management.daemon.disconnect.request", Schema::Unmodeled),
                            ("hub.management.daemon.permissions.update.request", Schema::Unmodeled),
                            ("diagnostics.request", Schema::Unmodeled),
                            ("plugin.catalog.get.request", Schema::Unmodeled),
                            ("plugin.list.request", Schema::Unmodeled),
                            ("plugin.logs.get.request", Schema::Unmodeled),
                            ("plugin.directory.install.request", Schema::Unmodeled),
                            ("plugin.directory.inspect.request", Schema::Unmodeled),
                            ("plugin.source.install.request", Schema::Unmodeled),
                            ("plugin.source.status.request", Schema::Unmodeled),
                            ("plugin.source.update.request", Schema::Unmodeled),
                            ("plugin.source.update.preview.request", Schema::Unmodeled),
                            ("plugin.source.update.apply.request", Schema::Unmodeled),
                            ("plugin.reload.request", Schema::Unmodeled),
                            ("plugin.enable.request", Schema::Unmodeled),
                            ("plugin.disable.request", Schema::Unmodeled),
                            ("plugin.remove.request", Schema::Unmodeled),
                            ("plugin.rpc.invoke.request", Schema::Unmodeled),
                            ("agent.timeline.append.request", Schema::Unmodeled),
                            ("agent.skills.get_status.request", Schema::Unmodeled),
                            ("agent.skills.reconcile.request", Schema::Unmodeled),
                            ("agent.skills.uninstall.request", Schema::Unmodeled),
                            ("agent.skills.save_selection.request", Schema::Unmodeled),
                            ("agent.skills.import_legacy_selection.request", Schema::Unmodeled),
                            ("get_daemon_config_request", Schema::Unmodeled),
                            ("set_daemon_config_request", Schema::Unmodeled),
                            ("read_project_config_request", Schema::Unmodeled),
                            ("write_project_config_request", Schema::Unmodeled),
                            ("dictation_stream_start", Schema::Unmodeled),
                            ("dictation_stream_chunk", Schema::Unmodeled),
                            ("dictation_stream_finish", Schema::Unmodeled),
                            ("dictation_stream_cancel", Schema::Unmodeled),
                            ("create_agent_request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("create_agent_request".to_owned()),
                                    ])),
                                    ("idempotencyKey", Schema::Lazy(|| &SHARED_3)),
                                    ("config", Schema::Lazy(|| &SHARED_4)),
                                    ("env", Schema::Lazy(|| &SHARED_17)),
                                    ("workspaceId", Schema::Lazy(|| &SHARED_18)),
                                    ("callerAgentId", Schema::Lazy(|| &SHARED_19)),
                                    ("worktreeName", Schema::Lazy(|| &SHARED_20)),
                                    ("initialPrompt", Schema::Lazy(|| &SHARED_21)),
                                    ("clientMessageId", Schema::Lazy(|| &SHARED_22)),
                                    ("outputSchema", Schema::Lazy(|| &SHARED_23)),
                                    ("images", Schema::Lazy(|| &SHARED_24)),
                                    ("attachments", Schema::Lazy(|| &SHARED_2)),
                                    ("git", Schema::Lazy(|| &SHARED_25)),
                                    ("worktree", Schema::Lazy(|| &SHARED_27)),
                                    ("autoArchive", Schema::Lazy(|| &SHARED_28)),
                                    ("labels", Schema::Lazy(|| &SHARED_29)),
                                    ("requestId", Schema::Lazy(|| &SHARED_30)),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("list_provider_models_request", Schema::Unmodeled),
                            ("list_provider_modes_request", Schema::Unmodeled),
                            ("list_provider_features_request", Schema::Unmodeled),
                            ("list_available_providers_request", Schema::Unmodeled),
                            ("get_providers_snapshot_request", Schema::Unmodeled),
                            ("refresh_providers_snapshot_request", Schema::Unmodeled),
                            ("provider_diagnostic_request", Schema::Unmodeled),
                            ("provider.usage.list.request", Schema::Unmodeled),
                            ("usage.list_reports.request", Schema::Unmodeled),
                            ("agent.resolve_usage_report.request", Schema::Unmodeled),
                            ("resume_agent_request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("resume_agent_request".to_owned()),
                                    ])),
                                    ("handle", Schema::Nullable(Box::new(Schema::Object(
                                        vec![
                                            ("provider", Schema::Lazy(|| &SHARED_5)),
                                            ("sessionId", Schema::String(vec![])),
                                            ("nativeHandle", Schema::Optional(Box::new(Schema::String(vec![])))),
                                            ("metadata", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("overrides", Schema::Optional(Box::new(Schema::Object(
                                        vec![
                                            ("provider", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_5)))),
                                            ("cwd", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_6)))),
                                            ("modeId", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_7)))),
                                            ("model", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_8)))),
                                            ("thinkingOptionId", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_9)))),
                                            ("featureValues", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_10)))),
                                            ("title", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_11)))),
                                            ("providerOptions", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_12)))),
                                            ("toolPolicy", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_14)))),
                                            ("systemPrompt", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_15)))),
                                            ("mcpServers", Schema::Optional(Box::new(Schema::Lazy(|| &SHARED_16)))),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("requestId", Schema::String(vec![])),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("import_agent_request", Schema::Unmodeled),
                            ("refresh_agent_request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("refresh_agent_request".to_owned()),
                                    ])),
                                    ("agentId", Schema::String(vec![])),
                                    ("requestId", Schema::String(vec![])),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("cancel_agent_request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("cancel_agent_request".to_owned()),
                                    ])),
                                    ("agentId", Schema::String(vec![])),
                                    ("requestId", Schema::Optional(Box::new(Schema::String(vec![])))),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("shutdown_server_request", Schema::Unmodeled),
                            ("restart_server_request", Schema::Unmodeled),
                            ("daemon.update.request", Schema::Unmodeled),
                            ("fetch_agent_timeline_request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("fetch_agent_timeline_request".to_owned()),
                                    ])),
                                    ("agentId", Schema::String(vec![])),
                                    ("requestId", Schema::String(vec![])),
                                    ("direction", Schema::Optional(Box::new(Schema::Enum(&["tail", "before", "after"])))),
                                    ("cursor", Schema::Optional(Box::new(Schema::Object(
                                        vec![
                                            ("epoch", Schema::String(vec![])),
                                            ("seq", Schema::Number(vec![
                                                NumberCheck::Int,
                                                NumberCheck::Gte(0.0),
                                            ])),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("limit", Schema::Optional(Box::new(Schema::Number(vec![
                                        NumberCheck::Int,
                                        NumberCheck::Gte(0.0),
                                    ])))),
                                    ("projection", Schema::Optional(Box::new(Schema::Enum(&["projected", "canonical"])))),
                                    ("mergeWindow", Schema::Optional(Box::new(Schema::Boolean))),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("agent.timeline.search.request", Schema::Unmodeled),
                            ("agent.timeline.list_prompts.request", Schema::Unmodeled),
                            ("agent.provider_subagents.list.request", Schema::Unmodeled),
                            ("agent.provider_subagents.timeline.get.request", Schema::Unmodeled),
                            ("agent.timeline.set_subscription.request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("agent.timeline.set_subscription.request".to_owned()),
                                    ])),
                                    ("agentIds", Schema::Array(Box::new(Schema::String(vec![])))),
                                    ("requestId", Schema::String(vec![])),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("agent.fork_context.request", Schema::Unmodeled),
                            ("set_agent_mode_request", Schema::Unmodeled),
                            ("set_agent_model_request", Schema::Unmodeled),
                            ("set_agent_thinking_request", Schema::Unmodeled),
                            ("set_agent_feature_request", Schema::Unmodeled),
                            ("agent.config.apply.request", Schema::Unmodeled),
                            ("agent.detach.request", Schema::Unmodeled),
                            ("agent.rewind.request", Schema::Unmodeled),
                            ("agent_permission_response", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("agent_permission_response".to_owned()),
                                    ])),
                                    ("agentId", Schema::String(vec![])),
                                    ("requestId", Schema::String(vec![])),
                                    ("response", Schema::Discriminated(
                                        "behavior",
                                        vec![
                                            ("allow", Schema::Object(
                                                vec![
                                                    ("behavior", Schema::Literal(vec![
                                                        JsValue::String("allow".to_owned()),
                                                    ])),
                                                    ("selectedActionId", Schema::Optional(Box::new(Schema::String(vec![])))),
                                                    ("updatedInput", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))),
                                                    ("updatedPermissions", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))))),
                                                ],
                                                UnknownKeys::Strip,
                                            )),
                                            ("deny", Schema::Object(
                                                vec![
                                                    ("behavior", Schema::Literal(vec![
                                                        JsValue::String("deny".to_owned()),
                                                    ])),
                                                    ("selectedActionId", Schema::Optional(Box::new(Schema::String(vec![])))),
                                                    ("message", Schema::Optional(Box::new(Schema::String(vec![])))),
                                                    ("interrupt", Schema::Optional(Box::new(Schema::Boolean))),
                                                ],
                                                UnknownKeys::Strip,
                                            )),
                                        ],
                                    )),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("checkout_status_request", Schema::Unmodeled),
                            ("checkout.diff.get.request", Schema::Unmodeled),
                            ("subscribe_checkout_diff_request", Schema::Unmodeled),
                            ("unsubscribe_checkout_diff_request", Schema::Unmodeled),
                            ("checkout_commit_request", Schema::Unmodeled),
                            ("checkout_merge_request", Schema::Unmodeled),
                            ("checkout_merge_from_base_request", Schema::Unmodeled),
                            ("checkout_pull_request", Schema::Unmodeled),
                            ("checkout_push_request", Schema::Unmodeled),
                            ("checkout.refresh.request", Schema::Unmodeled),
                            ("checkout.discard_changes.request", Schema::Unmodeled),
                            ("checkout_pr_create_request", Schema::Unmodeled),
                            ("checkout_pr_merge_request", Schema::Unmodeled),
                            ("checkout.forge.set_auto_merge.request", Schema::Unmodeled),
                            ("checkout.github.set_auto_merge.request", Schema::Unmodeled),
                            ("checkout.commits.list.request", Schema::Unmodeled),
                            ("checkout.commits.file_diff.request", Schema::Unmodeled),
                            ("checkout.forge.get_check_details.request", Schema::Unmodeled),
                            ("checkout.github.get_check_details.request", Schema::Unmodeled),
                            ("checkout_pr_status_request", Schema::Unmodeled),
                            ("pull_request_timeline_request", Schema::Unmodeled),
                            ("checkout_switch_branch_request", Schema::Unmodeled),
                            ("checkout.rename_branch.request", Schema::Unmodeled),
                            ("stash_save_request", Schema::Unmodeled),
                            ("stash_pop_request", Schema::Unmodeled),
                            ("stash_list_request", Schema::Unmodeled),
                            ("validate_branch_request", Schema::Unmodeled),
                            ("branch_suggestions_request", Schema::Unmodeled),
                            ("forge.search.request", Schema::Unmodeled),
                            ("github_search_request", Schema::Unmodeled),
                            ("directory_suggestions_request", Schema::Unmodeled),
                            ("paseo_worktree_list_request", Schema::Unmodeled),
                            ("paseo_worktree_archive_request", Schema::Unmodeled),
                            ("create_paseo_worktree_request", Schema::Unmodeled),
                            ("workspace_setup_status_request", Schema::Unmodeled),
                            ("workspace.setup.run.request", Schema::Unmodeled),
                            ("list_available_editors_request", Schema::Unmodeled),
                            ("open_in_editor_request", Schema::Unmodeled),
                            ("open_project_request", Schema::Unmodeled),
                            ("project.add.request", Schema::Unmodeled),
                            ("project.create_directory.request", Schema::Unmodeled),
                            ("workspace.github.search_repositories.request", Schema::Unmodeled),
                            ("project.github.clone.request", Schema::Unmodeled),
                            ("archive_workspace_request", Schema::Unmodeled),
                            ("workspace.create.request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("workspace.create.request".to_owned()),
                                    ])),
                                    ("workspaceId", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Format {
                    format: "regex",
                    pattern: "/^wks_[a-f0-9]{16}$/",
                    test: crate::id::is_workspace_id,
                    message: None,
                },
                                    ])))),
                                    ("agent", Schema::Optional(Box::new(Schema::Object(
                                        vec![
                                            ("config", Schema::Lazy(|| &SHARED_4)),
                                            ("env", Schema::Lazy(|| &SHARED_17)),
                                            ("callerAgentId", Schema::Lazy(|| &SHARED_19)),
                                            ("initialPrompt", Schema::Lazy(|| &SHARED_21)),
                                            ("clientMessageId", Schema::Lazy(|| &SHARED_22)),
                                            ("outputSchema", Schema::Lazy(|| &SHARED_23)),
                                            ("images", Schema::Lazy(|| &SHARED_24)),
                                            ("attachments", Schema::Lazy(|| &SHARED_31)),
                                            ("autoArchive", Schema::Lazy(|| &SHARED_28)),
                                            ("labels", Schema::Lazy(|| &SHARED_29)),
                                            ("agentId", Schema::Lazy(|| &SHARED_33)),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("subscribe", Schema::Optional(Box::new(Schema::Boolean))),
                                    ("requestId", Schema::String(vec![])),
                                    ("idempotencyKey", Schema::Optional(Box::new(Schema::String(vec![
                                        StringCheck::Min(1),
                                        StringCheck::Max(512),
                                    ])))),
                                    ("title", Schema::Optional(Box::new(Schema::String(vec![])))),
                                    ("firstAgentContext", Schema::Optional(Box::new(Schema::Object(
                                        vec![
                                            ("prompt", Schema::Optional(Box::new(Schema::String(vec![])))),
                                            ("attachments", Schema::Lazy(|| &SHARED_2)),
                                        ],
                                        UnknownKeys::Strip,
                                    )))),
                                    ("source", Schema::Discriminated(
                                        "kind",
                                        vec![
                                            ("directory", Schema::Object(
                                                vec![
                                                    ("kind", Schema::Literal(vec![
                                                        JsValue::String("directory".to_owned()),
                                                    ])),
                                                    ("path", Schema::String(vec![])),
                                                    ("projectId", Schema::Optional(Box::new(Schema::String(vec![])))),
                                                ],
                                                UnknownKeys::Strip,
                                            )),
                                            ("worktree", Schema::Object(
                                                vec![
                                                    ("kind", Schema::Literal(vec![
                                                        JsValue::String("worktree".to_owned()),
                                                    ])),
                                                    ("cwd", Schema::Optional(Box::new(Schema::String(vec![])))),
                                                    ("projectId", Schema::Optional(Box::new(Schema::String(vec![])))),
                                                    ("action", Schema::Optional(Box::new(Schema::Enum(&["branch-off", "checkout"])))),
                                                    ("refName", Schema::Optional(Box::new(Schema::String(vec![
                                                        StringCheck::Min(1),
                                                    ])))),
                                                    ("baseBranch", Schema::Optional(Box::new(Schema::String(vec![])))),
                                                    ("branchName", Schema::Optional(Box::new(Schema::String(vec![
                                                        StringCheck::Min(1),
                                                    ])))),
                                                    ("checkoutSource", Schema::Optional(Box::new(Schema::Lazy(|| &CHANGE_REQUEST_CHECKOUT_SOURCE)))),
                                                    ("githubPrNumber", Schema::Optional(Box::new(Schema::Number(vec![
                                                        NumberCheck::Int,
                                                        NumberCheck::Gt(0.0),
                                                    ])))),
                                                    ("worktreeSlug", Schema::Optional(Box::new(Schema::String(vec![])))),
                                                ],
                                                UnknownKeys::Strip,
                                            )),
                                        ],
                                    )),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("agent.create.request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("agent.create.request".to_owned()),
                                    ])),
                                    ("idempotencyKey", Schema::Lazy(|| &SHARED_3)),
                                    ("config", Schema::Lazy(|| &SHARED_4)),
                                    ("env", Schema::Lazy(|| &SHARED_17)),
                                    ("workspaceId", Schema::Lazy(|| &SHARED_18)),
                                    ("callerAgentId", Schema::Lazy(|| &SHARED_19)),
                                    ("worktreeName", Schema::Lazy(|| &SHARED_20)),
                                    ("initialPrompt", Schema::Lazy(|| &SHARED_21)),
                                    ("clientMessageId", Schema::Lazy(|| &SHARED_22)),
                                    ("outputSchema", Schema::Lazy(|| &SHARED_23)),
                                    ("images", Schema::Lazy(|| &SHARED_24)),
                                    ("attachments", Schema::Lazy(|| &SHARED_31)),
                                    ("git", Schema::Lazy(|| &SHARED_25)),
                                    ("worktree", Schema::Lazy(|| &SHARED_27)),
                                    ("autoArchive", Schema::Lazy(|| &SHARED_28)),
                                    ("labels", Schema::Lazy(|| &SHARED_29)),
                                    ("requestId", Schema::Lazy(|| &SHARED_30)),
                                    ("agentId", Schema::Lazy(|| &SHARED_33)),
                                    ("subscribe", Schema::Optional(Box::new(Schema::Boolean))),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("creation.subscribe.request", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("creation.subscribe.request".to_owned()),
                                    ])),
                                    ("requestId", Schema::String(vec![])),
                                    ("kind", Schema::Enum(&["workspace", "agent"])),
                                    ("idempotencyKey", Schema::String(vec![
                                        StringCheck::Min(1),
                                        StringCheck::Max(512),
                                    ])),
                                    ("subscribe", Schema::Optional(Box::new(Schema::Boolean))),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("workspace.clear_attention.request", Schema::Unmodeled),
                            ("workspace.mark_unread.request", Schema::Unmodeled),
                            ("file_explorer_request", Schema::Unmodeled),
                            ("fs.file.subscribe.request", Schema::Unmodeled),
                            ("fs.file.unsubscribe.request", Schema::Unmodeled),
                            ("fs.file.write.request", Schema::Unmodeled),
                            ("fs.entry.create.request", Schema::Unmodeled),
                            ("fs.entry.rename.request", Schema::Unmodeled),
                            ("fs.entry.duplicate.request", Schema::Unmodeled),
                            ("fs.entry.delete.request", Schema::Unmodeled),
                            ("project_icon_request", Schema::Unmodeled),
                            ("project.icon.get.request", Schema::Unmodeled),
                            ("file_download_token_request", Schema::Unmodeled),
                            ("file.upload.request", Schema::Unmodeled),
                            ("clear_agent_attention", Schema::Unmodeled),
                            ("client_heartbeat", Schema::Unmodeled),
                            ("ping", Schema::Object(
                                vec![
                                    ("type", Schema::Literal(vec![
                                        JsValue::String("ping".to_owned()),
                                    ])),
                                    ("requestId", Schema::String(vec![])),
                                    ("clientSentAt", Schema::Optional(Box::new(Schema::Number(vec![
                                        NumberCheck::Int,
                                    ])))),
                                ],
                                UnknownKeys::Strip,
                            )),
                            ("list_commands_request", Schema::Unmodeled),
                            ("register_push_token", Schema::Unmodeled),
                            ("push.unregister.request", Schema::Unmodeled),
                            ("list_terminals_request", Schema::Unmodeled),
                            ("subscribe_terminals_request", Schema::Unmodeled),
                            ("unsubscribe_terminals_request", Schema::Unmodeled),
                            ("create_terminal_request", Schema::Unmodeled),
                            ("terminal.rename.request", Schema::Unmodeled),
                            ("start_workspace_script_request", Schema::Unmodeled),
                            ("workspace.script.list.request", Schema::Unmodeled),
                            ("workspace.script.start.request", Schema::Unmodeled),
                            ("workspace.script.stop.request", Schema::Unmodeled),
                            ("subscribe_terminal_request", Schema::Unmodeled),
                            ("unsubscribe_terminal_request", Schema::Unmodeled),
                            ("terminal_input", Schema::Unmodeled),
                            ("kill_terminal_request", Schema::Unmodeled),
                            ("capture_terminal_request", Schema::Unmodeled),
                            ("chat/create", Schema::Unmodeled),
                            ("chat/list", Schema::Unmodeled),
                            ("chat/inspect", Schema::Unmodeled),
                            ("chat/delete", Schema::Unmodeled),
                            ("chat/post", Schema::Unmodeled),
                            ("chat/read", Schema::Unmodeled),
                            ("chat/wait", Schema::Unmodeled),
                            ("schedule/create", Schema::Unmodeled),
                            ("schedule/list", Schema::Unmodeled),
                            ("schedule/inspect", Schema::Unmodeled),
                            ("schedule/logs", Schema::Unmodeled),
                            ("schedule/pause", Schema::Unmodeled),
                            ("schedule/resume", Schema::Unmodeled),
                            ("schedule/delete", Schema::Unmodeled),
                            ("schedule/run-once", Schema::Unmodeled),
                            ("schedule/update", Schema::Unmodeled),
                            ("loop/run", Schema::Unmodeled),
                            ("loop/list", Schema::Unmodeled),
                            ("loop/inspect", Schema::Unmodeled),
                            ("loop/logs", Schema::Unmodeled),
                            ("loop/stop", Schema::Unmodeled),
                        ],
                    )),
                ],
                UnknownKeys::Strip,
            )),
        ],
    )
});

static SHARED_0: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Object(
        vec![
            ("generation", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("afterSeq", Schema::Optional(Box::new(Schema::Number(vec![
                NumberCheck::Int,
                NumberCheck::Gte(0.0),
            ])))),
        ],
        UnknownKeys::Strip,
    )
});

static SHARED_1: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Object(
        vec![
            ("data", Schema::String(vec![])),
            ("mimeType", Schema::String(vec![])),
        ],
        UnknownKeys::Strip,
    )
});

static SHARED_2: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Pipe(Box::new(Schema::Unknown), Box::new(Schema::Transform(Transform::NoIssue)))))
});

static SHARED_3: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![
        StringCheck::Min(1),
        StringCheck::Max(512),
    ])))
});

static SHARED_5: LazyLock<Schema> = LazyLock::new(|| {
    Schema::String(vec![])
});

static SHARED_6: LazyLock<Schema> = LazyLock::new(|| {
    Schema::String(vec![])
});

static SHARED_7: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![])))
});

static SHARED_8: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![])))
});

static SHARED_9: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![])))
});

static SHARED_10: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))
});

static SHARED_11: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Nullable(Box::new(Schema::Optional(Box::new(Schema::String(vec![
        StringCheck::Trim,
        StringCheck::Min(1),
        StringCheck::Max(200),
    ])))))
});

static SHARED_13: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Union(vec![
        Schema::String(vec![]),
        Schema::Number(vec![]),
        Schema::Boolean,
        Schema::Null,
        Schema::Array(Box::new(Schema::Lazy(|| &SHARED_13))),
        Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Lazy(|| &SHARED_13))),
    ])
});

static SHARED_12: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Lazy(|| &SHARED_13)))))
});

static SHARED_14: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Object(
        vec![
            ("preapproved", Schema::Array(Box::new(Schema::Object(
                vec![
                    ("kind", Schema::Literal(vec![
                        JsValue::String("mcp".to_owned()),
                    ])),
                    ("server", Schema::String(vec![
                        StringCheck::Trim,
                        StringCheck::Min(1),
                    ])),
                    ("tool", Schema::String(vec![
                        StringCheck::Trim,
                        StringCheck::Min(1),
                    ])),
                ],
                UnknownKeys::Strict,
            )))),
        ],
        UnknownKeys::Strict,
    )))
});

static SHARED_15: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![])))
});

static SHARED_16: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Discriminated(
        "type",
        vec![
            ("stdio", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("stdio".to_owned()),
                    ])),
                    ("command", Schema::String(vec![])),
                    ("args", Schema::Optional(Box::new(Schema::Array(Box::new(Schema::String(vec![])))))),
                    ("env", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::String(vec![])))))),
                    ("alwaysLoad", Schema::Optional(Box::new(Schema::Boolean))),
                ],
                UnknownKeys::Strip,
            )),
            ("http", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("http".to_owned()),
                    ])),
                    ("url", Schema::String(vec![])),
                    ("headers", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::String(vec![])))))),
                    ("alwaysLoad", Schema::Optional(Box::new(Schema::Boolean))),
                ],
                UnknownKeys::Strip,
            )),
            ("sse", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("sse".to_owned()),
                    ])),
                    ("url", Schema::String(vec![])),
                    ("headers", Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::String(vec![])))))),
                    ("alwaysLoad", Schema::Optional(Box::new(Schema::Boolean))),
                ],
                UnknownKeys::Strip,
            )),
        ],
    )))))
});

static SHARED_4: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Object(
        vec![
            ("provider", Schema::Lazy(|| &SHARED_5)),
            ("cwd", Schema::Lazy(|| &SHARED_6)),
            ("modeId", Schema::Lazy(|| &SHARED_7)),
            ("model", Schema::Lazy(|| &SHARED_8)),
            ("thinkingOptionId", Schema::Lazy(|| &SHARED_9)),
            ("featureValues", Schema::Lazy(|| &SHARED_10)),
            ("title", Schema::Lazy(|| &SHARED_11)),
            ("providerOptions", Schema::Lazy(|| &SHARED_12)),
            ("toolPolicy", Schema::Lazy(|| &SHARED_14)),
            ("systemPrompt", Schema::Lazy(|| &SHARED_15)),
            ("mcpServers", Schema::Lazy(|| &SHARED_16)),
        ],
        UnknownKeys::Strip,
    )
});

static SHARED_17: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::String(vec![])))))
});

static SHARED_18: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![])))
});

static SHARED_19: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![])))
});

static SHARED_20: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![])))
});

static SHARED_21: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![])))
});

static SHARED_22: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![])))
});

static SHARED_23: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::Unknown))))
});

static SHARED_24: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Lazy(|| &SHARED_1)))))
});

static CHANGE_REQUEST_CHECKOUT_SOURCE: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Object(
        vec![
            ("kind", Schema::Literal(vec![
                JsValue::String("change_request".to_owned()),
            ])),
            ("forge", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("number", Schema::Number(vec![
                NumberCheck::Int,
                NumberCheck::Gt(0.0),
            ])),
            ("projectPath", Schema::Optional(Box::new(Schema::String(vec![])))),
        ],
        UnknownKeys::Strip,
    )
});

static SHARED_25: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Object(
        vec![
            ("baseBranch", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("createNewBranch", Schema::Optional(Box::new(Schema::Boolean))),
            ("newBranchName", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("createWorktree", Schema::Optional(Box::new(Schema::Boolean))),
            ("worktreeSlug", Schema::Optional(Box::new(Schema::String(vec![])))),
            ("refName", Schema::Optional(Box::new(Schema::String(vec![
                StringCheck::Min(1),
            ])))),
            ("action", Schema::Optional(Box::new(Schema::Enum(&["branch-off", "checkout"])))),
            ("checkoutSource", Schema::Optional(Box::new(Schema::Lazy(|| &CHANGE_REQUEST_CHECKOUT_SOURCE)))),
            ("githubPrNumber", Schema::Optional(Box::new(Schema::Number(vec![
                NumberCheck::Int,
                NumberCheck::Gt(0.0),
            ])))),
        ],
        UnknownKeys::Strip,
    )))
});

static SHARED_27: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Discriminated(
        "mode",
        vec![
            ("branch-off", Schema::Object(
                vec![
                    ("mode", Schema::Literal(vec![
                        JsValue::String("branch-off".to_owned()),
                    ])),
                    ("newBranch", Schema::String(vec![
                        StringCheck::Min(1),
                    ])),
                    ("base", Schema::Optional(Box::new(Schema::String(vec![
                        StringCheck::Min(1),
                    ])))),
                ],
                UnknownKeys::Strip,
            )),
            ("checkout-branch", Schema::Object(
                vec![
                    ("mode", Schema::Literal(vec![
                        JsValue::String("checkout-branch".to_owned()),
                    ])),
                    ("branch", Schema::String(vec![
                        StringCheck::Min(1),
                    ])),
                ],
                UnknownKeys::Strip,
            )),
            ("checkout-pr", Schema::Object(
                vec![
                    ("mode", Schema::Literal(vec![
                        JsValue::String("checkout-pr".to_owned()),
                    ])),
                    ("prNumber", Schema::Number(vec![
                        NumberCheck::Int,
                        NumberCheck::Gt(0.0),
                    ])),
                ],
                UnknownKeys::Strip,
            )),
        ],
    )))
});

static SHARED_28: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Boolean))
});

static SHARED_29: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Default(Box::new(Schema::Record(Box::new(Schema::String(vec![])), Box::new(Schema::String(vec![])))), "{}")
});

static SHARED_30: LazyLock<Schema> = LazyLock::new(|| {
    Schema::String(vec![])
});

static REVIEW_ATTACHMENT_CONTEXT_LINE: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Object(
        vec![
            ("oldLineNumber", Schema::Nullable(Box::new(Schema::Number(vec![
                NumberCheck::Int,
                NumberCheck::Gt(0.0),
            ])))),
            ("newLineNumber", Schema::Nullable(Box::new(Schema::Number(vec![
                NumberCheck::Int,
                NumberCheck::Gt(0.0),
            ])))),
            ("type", Schema::Enum(&["add", "remove", "context"])),
            ("content", Schema::String(vec![])),
        ],
        UnknownKeys::Strip,
    )
});

static SHARED_31: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::Array(Box::new(Schema::Discriminated(
        "type",
        vec![
            ("forge_change_request", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("forge_change_request".to_owned()),
                    ])),
                    ("mimeType", Schema::Literal(vec![
                        JsValue::String("application/paseo-forge-change-request".to_owned()),
                    ])),
                    ("forge", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::String(vec![])))), r#""github""#)),
                    ("number", Schema::Number(vec![
                        NumberCheck::Int,
                        NumberCheck::Gt(0.0),
                    ])),
                    ("title", Schema::String(vec![])),
                    ("url", Schema::String(vec![])),
                    ("body", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("projectPath", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("baseRefName", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("headRefName", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                ],
                UnknownKeys::Strip,
            )),
            ("forge_issue", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("forge_issue".to_owned()),
                    ])),
                    ("mimeType", Schema::Literal(vec![
                        JsValue::String("application/paseo-forge-issue".to_owned()),
                    ])),
                    ("forge", Schema::Default(Box::new(Schema::Optional(Box::new(Schema::String(vec![])))), r#""github""#)),
                    ("number", Schema::Number(vec![
                        NumberCheck::Int,
                        NumberCheck::Gt(0.0),
                    ])),
                    ("title", Schema::String(vec![])),
                    ("url", Schema::String(vec![])),
                    ("body", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("projectPath", Schema::Optional(Box::new(Schema::String(vec![])))),
                ],
                UnknownKeys::Strip,
            )),
            ("github_pr", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("github_pr".to_owned()),
                    ])),
                    ("mimeType", Schema::Literal(vec![
                        JsValue::String("application/github-pr".to_owned()),
                    ])),
                    ("number", Schema::Number(vec![
                        NumberCheck::Int,
                        NumberCheck::Gt(0.0),
                    ])),
                    ("title", Schema::String(vec![])),
                    ("url", Schema::String(vec![])),
                    ("body", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("baseRefName", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("headRefName", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                ],
                UnknownKeys::Strip,
            )),
            ("github_issue", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("github_issue".to_owned()),
                    ])),
                    ("mimeType", Schema::Literal(vec![
                        JsValue::String("application/github-issue".to_owned()),
                    ])),
                    ("number", Schema::Number(vec![
                        NumberCheck::Int,
                        NumberCheck::Gt(0.0),
                    ])),
                    ("title", Schema::String(vec![])),
                    ("url", Schema::String(vec![])),
                    ("body", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                ],
                UnknownKeys::Strip,
            )),
            ("text", Schema::Pipe(Box::new(Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("text".to_owned()),
                    ])),
                    ("mimeType", Schema::Literal(vec![
                        JsValue::String("text/plain".to_owned()),
                    ])),
                    ("contextKind", Schema::Optional(Box::new(Schema::String(vec![])))),
                    ("title", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("text", Schema::String(vec![])),
                    ("externalResource", Schema::Optional(Box::new(Schema::Object(
                        vec![
                            ("provider", Schema::String(vec![])),
                            ("providerLabel", Schema::String(vec![])),
                            ("resourceType", Schema::String(vec![])),
                            ("id", Schema::String(vec![])),
                            ("identifier", Schema::String(vec![])),
                            ("title", Schema::String(vec![])),
                            ("url", Schema::String(vec![])),
                        ],
                        UnknownKeys::Strip,
                    )))),
                ],
                UnknownKeys::Strip,
            )), Box::new(Schema::Transform(Transform::NoIssue)))),
            ("review", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("review".to_owned()),
                    ])),
                    ("mimeType", Schema::Literal(vec![
                        JsValue::String("application/paseo-review".to_owned()),
                    ])),
                    ("cwd", Schema::String(vec![])),
                    ("mode", Schema::Enum(&["uncommitted", "base"])),
                    ("baseRef", Schema::Optional(Box::new(Schema::Nullable(Box::new(Schema::String(vec![])))))),
                    ("comments", Schema::Array(Box::new(Schema::Object(
                        vec![
                            ("filePath", Schema::String(vec![])),
                            ("side", Schema::Enum(&["old", "new"])),
                            ("lineNumber", Schema::Number(vec![
                                NumberCheck::Int,
                                NumberCheck::Gt(0.0),
                            ])),
                            ("body", Schema::String(vec![])),
                            ("context", Schema::Object(
                                vec![
                                    ("hunkHeader", Schema::String(vec![])),
                                    ("targetLine", Schema::Lazy(|| &REVIEW_ATTACHMENT_CONTEXT_LINE)),
                                    ("lines", Schema::Array(Box::new(Schema::Lazy(|| &REVIEW_ATTACHMENT_CONTEXT_LINE)))),
                                ],
                                UnknownKeys::Strip,
                            )),
                        ],
                        UnknownKeys::Strip,
                    )))),
                ],
                UnknownKeys::Strip,
            )),
            ("uploaded_file", Schema::Object(
                vec![
                    ("type", Schema::Literal(vec![
                        JsValue::String("uploaded_file".to_owned()),
                    ])),
                    ("id", Schema::String(vec![])),
                    ("fileName", Schema::String(vec![])),
                    ("mimeType", Schema::String(vec![])),
                    ("size", Schema::Number(vec![
                        NumberCheck::Int,
                        NumberCheck::Gte(0.0),
                    ])),
                    ("path", Schema::String(vec![])),
                ],
                UnknownKeys::Strip,
            )),
        ],
    )))))
});

static SHARED_33: LazyLock<Schema> = LazyLock::new(|| {
    Schema::Optional(Box::new(Schema::String(vec![
        StringCheck::Format {
    format: "uuid",
    pattern: "/^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/",
    test: crate::id::is_zod_uuid,
    message: None,
},
    ])))
});
