#!/usr/bin/env node
// Generates crates/spocky-contracts/src/js_case_tables.rs: the data behind
// String.prototype.toLowerCase as node v22.20.0 (Unicode 16.0, ICU 77.1) runs
// it. The Rust toolchain's own Unicode tables move ahead of node's (Unicode
// 17 adds lowercase pairs node does not have), so the mappings and the two
// Final_Sigma properties (Cased, Case_Ignorable) are read from node itself.
//
// Usage (Node 22.20.0, the binary pinned by the slice harness):
//   ~/.nvm/versions/node/v22.20.0/bin/node scripts/phase3/contracts-case.mjs [--check]
//
// --check regenerates in memory and exits 1 if the committed file differs.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const NODE_VERSION = "v22.20.0";
const here = dirname(fileURLToPath(import.meta.url));
const outputPath = join(resolve(here, "../.."), "crates/spocky-contracts/src/js_case_tables.rs");

function fail(message) {
  process.stderr.write(`contracts-case: ${message}\n`);
  process.exit(2);
}

const check = process.argv.includes("--check");
for (const arg of process.argv.slice(2)) if (arg !== "--check") fail(`unknown argument ${arg}`);
if (process.version !== NODE_VERSION) fail(`expected node ${NODE_VERSION}, running ${process.version}`);

const isScalar = (code) => code < 0xd800 || code > 0xdfff;
const cased = /^\p{Cased}$/u;
const ignorable = /^\p{Case_Ignorable}$/u;

const single = [];
const multi = [];
const casedRanges = [];
const ignorableRanges = [];
const extend = (ranges, code) => {
  const last = ranges[ranges.length - 1];
  if (last && last[1] + 1 === code) last[1] = code;
  else ranges.push([code, code]);
};
for (let code = 0; code <= 0x10ffff; code += 1) {
  if (!isScalar(code)) continue;
  const text = String.fromCodePoint(code);
  const lower = text.toLowerCase();
  if (lower !== text) {
    const points = [...lower].map((character) => character.codePointAt(0));
    if (points.length === 1) single.push([code, points[0]]);
    else multi.push([code, points]);
  }
  if (cased.test(text)) extend(casedRanges, code);
  if (ignorable.test(text)) extend(ignorableRanges, code);
}

const hex = (value) => `0x${value.toString(16).toUpperCase().padStart(4, "0")}`;
const rows = (items, format, perLine) => {
  const lines = [];
  for (let index = 0; index < items.length; index += perLine) {
    lines.push(`    ${items.slice(index, index + perLine).map(format).join(" ")}`);
  }
  return lines.join("\n");
};

const text = `// Generated by scripts/phase3/contracts-case.mjs; do not edit.
//! Case data of node v22.20.0 (Unicode ${process.versions.unicode}, ICU ${process.versions.icu}) for
//! [\`crate::text::js_to_lowercase\`]: every code point whose
//! \`String.prototype.toLowerCase\` differs from itself, and the \`Cased\` and
//! \`Case_Ignorable\` ranges \`Final_Sigma\` reads.

/// The Unicode version of the node these tables were read from.
pub const UNICODE_VERSION: &str = "${process.versions.unicode}";

/// \`(code point, lowercase)\` for every code point that lowercases to exactly
/// one code point, sorted by code point. U+03A3 is its non-final mapping.
pub static LOWER_SINGLE: [(u32, u32); ${single.length}] = [
${rows(single, ([from, to]) => `(${hex(from)}, ${hex(to)}),`, 4)}
];

/// \`(code point, lowercase)\` for every code point that lowercases to more
/// than one code point, sorted by code point.
pub static LOWER_MULTI: [(u32, &[u32]); ${multi.length}] = [
${rows(multi, ([from, to]) => `(${hex(from)}, &[${to.map(hex).join(", ")}]),`, 1)}
];

/// Inclusive \`Cased\` ranges, sorted.
pub static CASED: [(u32, u32); ${casedRanges.length}] = [
${rows(casedRanges, ([from, to]) => `(${hex(from)}, ${hex(to)}),`, 4)}
];

/// Inclusive \`Case_Ignorable\` ranges, sorted.
pub static CASE_IGNORABLE: [(u32, u32); ${ignorableRanges.length}] = [
${rows(ignorableRanges, ([from, to]) => `(${hex(from)}, ${hex(to)}),`, 4)}
];
`;

if (check) {
  if (readFileSync(outputPath, "utf8") !== text) {
    process.stderr.write("contracts-case: js_case_tables.rs is stale; rerun without --check\n");
    process.exit(1);
  }
  process.stdout.write(`contracts-case: ${outputPath} is current\n`);
} else {
  writeFileSync(outputPath, text);
  process.stdout.write(`contracts-case: wrote ${outputPath}\n`);
}
