[package]
name = "spocky-contracts"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
rust-version = "1.94"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["float_roundtrip", "preserve_order", "raw_value"] }
ryu-js = "1.0.3"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "deny"
pedantic = "deny"
